### ISSUE TITLE
Customise Scaffold to take first line of document as title

### ISSUE THREAD

**Issue by TJMusiitwa** [memspace/zefyr#100]
Hello, thank you for this amazing project. It came just in time for my project. However, i was curious if there was a way to implement a sort of detection where the content of the first line becomes the title of the document, such that I could be able to use that as a field in the local storage db.

It could have a similar implementation to the full-screen dialog example from the official flutter gallery app, where it is a stream captured from an input/first line of the document and then relayed to the Appbar.
[Full Screen Dialog Example from Flutter Gallery](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/full_screen_dialog_demo.dart)
If you download the Flutter Gallery App > Material> Dialogs>Full Screen Dialog, you can get to see what I am implying.

The ZefyrField is a start, however it seems we can't customise the ZefyrScaffold where the Zefyr title and icon live to achieve a similar result.
Thanks.

**Comment by fschlosser** [comment]
Hi @TJMusiitwa, I had a similar problem and solved it this way:

```
String plaintext = document.lookupLine(0).node.toPlainText();
```

The '0' mean the index of the very first character of the document. So when calling the node, you will get the first node of the document. With the 'toPlainText()' you remove the the markup-language stuff and just get the text. You can also limit it with a substring until the first newline '\n' like this:

```
String plaintext = document.lookupLine(0).node.toPlainText();
String firstLine = plaintext.substring(0, plaintext.indexOf("\n"));
```

I hope that helps. If you know a better way to solve that, please let us know. Thank you!

**Comment by pulyaevskiy** [comment]
ZefyrScaffold is no longer in zefyr `^1.0.0-rc.x` so I suppose this is not relevant anymore.
