### ISSUE TITLE
Crash in editable_box.dart

### ISSUE THREAD

**Issue by valeIT** [memspace/zefyr#101]
Hey, loving the framework. 

I run into a crashing bug fairly often on Tablets only. In editable_box.dart the function "containsCaret" crashes when accessing "node.documentOffset" (which is equal to null). Let me know if I can help further with debugging it.

For now as a workaround I've added:

`if (node == null) {
      return false;
    }
    if (node.documentOffset == null) {
      return false;
    }`

But it is obviously just a hack not to make it crash, nothing else.

## Steps to Reproduce

1. Paste something long
2. Use backspace a lot

## Logs

<img width="783" alt="Screenshot 2019-04-25 at 18 19 36" src="https://user-images.githubusercontent.com/2276140/56752701-2de9fa80-6789-11e9-907b-0b162f99aaa9.png">
<img width="1680" alt="Screenshot 2019-04-25 at 18 20 35" src="https://user-images.githubusercontent.com/2276140/56752702-2de9fa80-6789-11e9-8fa3-55a1ee1979d6.png">

flutter doctor -v
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.4 18E226, locale en-IT)
    • Flutter version 1.4.9-hotfix.1 at /Users/valentinourbano/flutter
    • Framework revision 88fa7ea403 (2 weeks ago), 2019-04-11 14:01:46 -0700
    • Engine revision 4737fc5cd8
    • Dart version 2.2.1 (build 2.2.1-dev.4.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/valentinourbano/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/valentinourbano/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/valentinourbano/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • SM T825 • 96e158a4 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

```
```

Pretty new to Flutter so don't know to get better logs. Let me know if I can be of any further help.

**Comment by pulyaevskiy** [comment]
Wondering if this is still an issue after upgrading to latest version of Zefyr? There was a couple of fixes that may have resolved this for you.

**Comment by valeIT** [comment]
Haven't seen in for a few months so we can close it fow now. Will let you know if it pops back up again.
