### ISSUE TITLE
How to get contents?

### ISSUE THREAD

**Issue by Luppakorva** [memspace/zefyr#102]
Sorry about the very simple question. Tried to find the answer for the past hour but no luck. Am sure I'm missing something but just can't figure it out.

In TextField we get the content of the field with the following method: 

`controller.text`

How can I get the content with Zefyr?

**Comment by Luppakorva** [comment]
Well indeed it was simple. Had another problem in the code preventing me to get .document. Closing.

**Comment by Zeeshan0201** [comment]
@Luppakorva have you find the solution? Actually I am also not able to find the text...
