### ISSUE TITLE
proper way to serialize/de-serialize Zefyr document?

### ISSUE THREAD

**Issue by cc123** [memspace/zefyr#104]
I'll apologize up front - I'm sure I've missed something very simple here, but I can't seem to successfully read and display a Zefyr document which I've previously saved to json

1. I get the json version of the zefyr doc in json format and save it somewhere:
var jsondoc = _zcontroller.document.toJson();
 
2a.
var doc2 = NotusDocument.fromJson(json.decode(jsondoc) as List);
...
ZefyrView(document: doc2, ...) 

(exception, see image):
![1](https://user-images.githubusercontent.com/867228/57181900-95254000-6e56-11e9-935c-98d5bad0d7de.jpg)

-OR-

2b.
var doc2 = NotusDocument.fromJson(jsondoc);
...
ZefyrView(document: doc2, ...) 

(exception, see image):
![2](https://user-images.githubusercontent.com/867228/57181902-a1a99880-6e56-11e9-8307-ff0efaa67263.jpg)

(btw - I'm using the view example provided in the repo, and everything works fine when I use the long hard-coded delta string (called doc) in that example. It only breaks when I try using my own stored data.

**Comment by feschaffa** [comment]
Hey there!

Import dart:convert on your script, then, when saving or reading, do the following:

To save the document:
`String json_doc = json.encode(_zcontroller.document.toJson)`

And to display it:
`NotusDocument _doc = NotusDocument.fromJson(json.decode(json_doc) as List)`
`ZefyrView(document: _doc)`

The `toJson` function returns kind of a List as far as I know, not a String, so you have to convert it to the proper json format before storing on your db.

Hope it helps.

**Comment by pulyaevskiy** [comment]
> `String json_doc = json.encode(_zcontroller.document.toJson)`

Hint: there is no need to call `toJson` on the document. Simple `jsonEncode(_zcontroller.document);` would do.

Docs: https://www.dartlang.org/guides/libraries/library-tour#decoding-and-encoding-json (search for `toJson`).

**Comment by cc123** [comment]
Many thanks to both of you!

**Comment by pulyaevskiy** [comment]
See updated Quick Start tutorial for details of how to load and save from/to JSON.
