### ISSUE TITLE
Focus Error

### ISSUE THREAD

**Issue by VincentHu76** [memspace/zefyr#111]
## Steps to Reproduce

When the text content of a single paragraph exceeds one screen, the user moving the input focus causes the screen to scroll to an area outside the focus.

## Logs

![1](https://user-images.githubusercontent.com/19338960/58167918-a1672500-7cbf-11e9-93d8-3e68f50bd8db.png)
![2](https://user-images.githubusercontent.com/19338960/58168139-23574e00-7cc0-11e9-92e3-c015aed444e2.png)

**Comment by Skquark** [comment]
This bug hasn't been addressed in a while, but we're still experiencing it.  It's the one glitch remaining that makes using this difficult when typing, and makes it feel not ready for production use.  It's fine for the first page, but when a document is longer, it keeps jumping around and shifting focus up & down.  Any thoughts on how to fix this?  My guess is something with the FocusNode handling.

**Comment by raj457036** [comment]
Check my comments on #171 . I also solve this problem by that method.

**Comment by pulyaevskiy** [comment]
I believe this should be addressed in `1.0-dev` branch. Closing.
