### ISSUE TITLE
Is zefyr a web view flutter adaptation of Quill.js delta??

### ISSUE THREAD

**Issue by jarl-alejandro** [memspace/zefyr#122]
is only a question...
Is zefyr a web view flutter  adaptation  of Quill.js delta??

**Comment by pulyaevskiy** [comment]
No, Zefyr is written fully in Dart and it’s just another Flutter widget, there is no web view involved.

**Comment by jarl-alejandro** [comment]
Cool, 
Does it work collaboratively in real time?
Can Offlane synchronization be done?

**Comment by pulyaevskiy** [comment]
Yes it is possible to implement an OT server to handle synchronization between multiple clients. This is mostly enabled but the Deltas library and has little to do with the editor itself.

That said actual implementation of OT server is not part of this library so users will have to do it themselves.

I was able to implement it in my own project.

**Comment by pulyaevskiy** [comment]
Closing this as resolved.
