### ISSUE TITLE
Error while building the app.

### ISSUE THREAD

**Issue by VickySalunkhe** [memspace/zefyr#123]
## Steps to Reproduce

Errors are coming while building the app

## Logs
Compiler message:
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/editable_text.dart:102:28: Error: The method 'reparentIfNeeded' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///C:/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'reparentIfNeeded'.
    FocusScope.of(context).reparentIfNeeded(focusNode);
                           ^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/selection.dart:483:22: Error: Too few positional arguments: 5 required, 4 given.
        .buildToolbar(context, editingRegion, midpoint, widget.delegate);
                     ^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/input.dart:153:18: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
        context: 'while updating editing value',

Compiler failed on D:\vicky\Work\Flutter-Test-Apps-master\write_india\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 647

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm64'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

## flutter doctor -v

S D:\vicky\Work\Flutter-Test-Apps-master\write_india> flutter doctor -v
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.6.3 at C:\flutter
    • Framework revision bc7bc94083 (7 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Vicky Salunkhe\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.0)
    • VS Code at C:\Users\Vicky Salunkhe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Redmi Note 4 • 9441dce20803 • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by pulyaevskiy** [comment]
This should be fixed in just released 0.6.0. Closing as resolved.
