### ISSUE TITLE
Zefyr stops building after upgrade to Flutter v1.7.8+hotfix.3

### ISSUE THREAD

**Issue by cc123** [memspace/zefyr#125]
I upgraded Flutter today -> v1.7.8, and Zefyr stopped building.

Flutter says:

Compiler message:
file:///d:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/selection.dart:42:7: Error: The non-abstract class '_ZefyrSelectionOverlayState' is missing implementations for these members:
 - TextSelectionDelegate.copyEnabled
 - TextSelectionDelegate.cutEnabled
 - TextSelectionDelegate.pasteEnabled
 - TextSelectionDelegate.selectAllEnabled
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ZefyrSelectionOverlayState extends State<ZefyrSelectionOverlay>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///d:/flutter/packages/flutter/lib/src/services/text_input.dart:596:12: Context: 'TextSelectionDelegate.copyEnabled' is defined here.
  bool get copyEnabled => true;
           ^^^^^^^^^^^
file:///d:/flutter/packages/flutter/lib/src/services/text_input.dart:593:12: Context: 'TextSelectionDelegate.cutEnabled' is defined here.
  bool get cutEnabled => true;
           ^^^^^^^^^^
file:///d:/flutter/packages/flutter/lib/src/services/text_input.dart:599:12: Context: 'TextSelectionDelegate.pasteEnabled' is defined here.
  bool get pasteEnabled => true;
           ^^^^^^^^^^^^
file:///d:/flutter/packages/flutter/lib/src/services/text_input.dart:602:12: Context: 'TextSelectionDelegate.selectAllEnabled' is defined here.
  bool get selectAllEnabled => true;
           ^^^^^^^^^^^^^^^^
file:///d:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/rich_text.dart:184:26: Error: The parameter 'value' of the method 'RenderZefyrParagraph.text' has type 'TextSpan', which does not match the corresponding type, 'InlineSpan', in the overridden method, 'RenderParagraph.text'.
 - 'TextSpan' is from 'package:flutter/src/painting/text_span.dart' ('file:///d:/flutter/packages/flutter/lib/src/painting/text_span.dart').
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('file:///d:/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Change to a supertype of 'InlineSpan', or, for a covariant parameter, a subtype.
  void set text(TextSpan value) {
                         ^
file:///d:/flutter/packages/flutter/lib/src/rendering/paragraph.dart:115:7: Context: This is the overridden method ('text').
  set text(InlineSpan value) {
      ^
file:///d:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/editable_text.dart:102:28: Error: The method 'reparentIfNeeded' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///d:/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'reparentIfNeeded'.
    FocusScope.of(context).reparentIfNeeded(focusNode);
                           ^^^^^^^^^^^^^^^^
file:///d:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/selection.dart:483:22: Error: Too few positional arguments: 6 required, 4 given.
        .buildToolbar(context, editingRegion, midpoint, widget.delegate);
                     ^
file:///d:/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.5.0/lib/src/widgets/input.dart:153:18: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///d:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
        context: 'while updating editing value',
                 ^
Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script 'd:\wintools\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 638

* What went wrong:
Execution failed for task ':app:compileflutterBuildReleaseArm'.
> Process 'command 'd:\wintools\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       9.6s
Gradle task assembleRelease failed with exit code 1

Flutter doctor says:

flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at d:\flutter
    • Framework revision b712a172f9 (21 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\v\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\v\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by janiokq** [comment]
I need this

**Comment by therichiekumar** [comment]
@cc123 @janiokq Can you resolve this?

**Comment by janiokq** [comment]
@therichiekumar     https://github.com/memspace/zefyr/pull/117    this  Request to merge

**Comment by therichiekumar** [comment]
@janiokq It works, but i get new error.  **The method 'ZefyrView' isn't defined for the class '_ViewArticleState'.**

**Comment by pulyaevskiy** [comment]
Sorry everyone for the delay here. I just published Zefyr `0.6.0` which works with Flutter `1.7.8`.
There was also one regression after upgrade where positioning of selection handles was off, I addressed this as well.

Closing this as resolved. Feel free to open new issues if something is still not working on your end.

**Comment by cc123** [comment]
awesome, thanks so much!
