### ISSUE TITLE
How to use text input and toolbar separately

### ISSUE THREAD

**Issue by ivtod** [memspace/zefyr#13]
Hi @pulyaevskiy,
first of all thanks for this great RTE!

How can I use the editor and the toolbar separately? I can see in your source code that `ZefyrEditor` is composed by a `ZefyrEditableText` into an Expanded widget and a `ZefyrToolbar`; how can I use them to achieve what you can see in the image below? 

![zefyr-editor](https://user-images.githubusercontent.com/8202482/43066066-f17964c2-8e63-11e8-88cd-2d5d3f025f80.jpg)

I need to use the editor ("inline" and not "fullscreen") in a screen with other widgets (post title, post subtitle, images carousel, ..) and maybe set the toolbar in a different and custom position.

Could you please provide some example?

Thank you!

**Comment by pulyaevskiy** [comment]
Thanks for taking time to submit this issue.

It is currently not possible to use Zefyr text input without the toolbar, unfortunately.

I did have a plan to implement separate `ZefyrField` which behaves closer to regular `TextField` and embeds toolbar into the scaffold's Overlay. So this is definitely something I'd like to address.

Though I must say that this is not high on my priority list currently. I will post an update here when I have any progress on this.

As a workaround, it should be possible to put `ZefyrEditor` inside of a `ConstrainedBox` which has fixed height. However toolbar would be inside of that constrained box which is far from ideal.

**Comment by ivtod** [comment]
Yes unfortunately it's far from ideal.
Thanks ;)

**Comment by aldo** [comment]
Hi @pulyaevskiy,
any update on this?

**Comment by LiliDelo** [comment]
@pulyaevskiy definitely a must-have feature! Any news on this? 
Thanks for your great job

**Comment by pulyaevskiy** [comment]
Hey guys, sorry for a bit of a silence here. It is on my radar but I'm not actively working on this yet.
I'll make sure to post updates here when I get to this.

In the meantime please make sure to +1 the post if you haven't yet. I'll be prioritizing work based on popularity.

**Comment by LeafSW** [comment]
I agree, definitely a must-have feature. This would allow to create a completely custom ux.
I wonder how users are actually using it, for example, how can you create a view that allows user to post a blog post with title and body?

**Comment by pulyaevskiy** [comment]
This looks like the most popular request so far. I'll try to allocate some time in coming weeks for it.

Thanks everyone for your feedback. Much appreciated.

**Comment by pulyaevskiy** [comment]
Just an FYI that some work towards this feature started in #40. Getting closer.

**Comment by ivtod** [comment]
Great @pulyaevskiy, can't wait to try it out

**Comment by pulyaevskiy** [comment]
New version of Zefyr (0.3.0) is out and provides a way to embed the editor into complex layout.

Please see changelog for more details as this is a breaking change. I also wrote a short blog post with more background on this:
https://medium.com/@pulyaevskiy/zefyr-0-3-embedding-and-decorating-456e634449a6

Closing this as resolved. Feel free to open new issues if you find something is not working as expected.

Thanks everyone for your feedback!

**Comment by ivtod** [comment]
Hi @pulyaevskiy, tried it and it works great.
Is it possible to have the ZefyrField height to not be fixed but to expand based on the content? Just like a TextField behavior setting maxLines to null to allow it to auto grow vertically.

**Comment by pulyaevskiy** [comment]
@ivtod glad to see it worked well for you!

Please submit a separate issue re: maxLines. Currently it's not possible but it seems like a reasonable request. It might be a bit more involved than with regular text fields because in Zefyr there is no fixed line height for all text. We cannot know in advance what would be the editor's height based only on `maxLines` value. Additionally when user applies different styles editor's height may jump as well, which would be weird UX.

As an alternative we can introduce `maxHeight` instead with similar semantics.

**Comment by aldo** [comment]
Yes I agree, it sounds like a reasonable request because in addition to features or functionality improvement, I think that what would be great about this package is to allow a full ui/ux customization (like having and editor composed by multiple block types as richtext using zefyr and video, images, images grid, slideshow, ... using other custom widgets/packages).

How would you use `maxHeight`?

**Comment by pulyaevskiy** [comment]
Definitely. But again I'd encourage everyone to submit separate issues for each feature they'd like to see. This way we can have focused discussion and collect +1s which would help in prioritizing future work. Thanks!

This current issue has been implemented, released and closed.
