### ISSUE TITLE
Failing to build on flutter master channel

### ISSUE THREAD

**Issue by abhee4** [memspace/zefyr#132]
## Steps to Reproduce

1. Used the example from https://github.com/memspace/zefyr, tried to integrate to my own project as well.
2. Ran on the target device

## Logs

Launching lib\main.dart on Pixel 3 in debug mode...

Compiler message:
file:///C:/Users/user/Documents/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/selection.dart:42:7: Error: The non-abstract class '_ZefyrSelectionOverlayState' is missing implementations for these members:
 - TextSelectionDelegate.copyEnabled
 - TextSelectionDelegate.cutEnabled
 - TextSelectionDelegate.pasteEnabled
 - TextSelectionDelegate.selectAllEnabled
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ZefyrSelectionOverlayState extends State<ZefyrSelectionOverlay>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:596:12: Context: 'TextSelectionDelegate.copyEnabled' is defined here.
  bool get copyEnabled => true;
           ^^^^^^^^^^^
file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:593:12: Context: 'TextSelectionDelegate.cutEnabled' is defined here.
  bool get cutEnabled => true;
           ^^^^^^^^^^
file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:599:12: Context: 'TextSelectionDelegate.pasteEnabled' is defined here.
  bool get pasteEnabled => true;
           ^^^^^^^^^^^^
file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/services/text_input.dart:602:12: Context: 'TextSelectionDelegate.selectAllEnabled' is defined here.
  bool get selectAllEnabled => true;
           ^^^^^^^^^^^^^^^^
file:///C:/Users/user/Documents/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/rich_text.dart:184:26: Error: The parameter 'value' of the method 'RenderZefyrParagraph.text' has type 'TextSpan', which does not match the corresponding type, 'InlineSpan', in the overridden method, 'RenderParagraph.text'.
 - 'TextSpan' is from 'package:flutter/src/painting/text_span.dart' ('file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/painting/text_span.dart').
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Change to a supertype of 'InlineSpan', or, for a covariant parameter, a subtype.
  void set text(TextSpan value) {
                         ^
file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/rendering/paragraph.dart:115:7: Context: This is the overridden method ('text').
  set text(InlineSpan value) {
      ^
file:///C:/Users/user/Documents/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/editable_text.dart:102:28: Error: The method 'reparentIfNeeded' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'reparentIfNeeded'.
    FocusScope.of(context).reparentIfNeeded(focusNode);
                           ^^^^^^^^^^^^^^^^
file:///C:/Users/user/Documents/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/selection.dart:483:22: Error: Too few positional arguments: 6 required, 4 given.
        .buildToolbar(context, editingRegion, midpoint, widget.delegate);
                     ^
file:///C:/Users/user/Documents/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/input.dart:153:18: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/Users/user/Documents/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
        context: 'while updating editing value',
                 ^
Compiler failed on C:\Users\user\Desktop\example\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\user\Documents\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugArm64'.
> Process 'command 'C:\Users\user\Documents\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

$ flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.267], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\Users\user\Documents\flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700 
    • Engine revision fee001c93f
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • Pixel 3 • XXXXXXXXXX • android-arm64 • Android 10 (API 29)

• No issues found!

**Comment by BroPet89** [comment]
I am also on "**Channel stable**, v1.7.8+hotfix.4, " and having the same issue.  The error report start the same but I end up with an:

**Comment by pulyaevskiy** [comment]
This should be fixed in `0.6.x`, have you tried upgrading?

**Comment by abhee4** [comment]
I did. And now it works fine. Thanks for the update.
