### ISSUE TITLE
please update image_picker version~~~thanks!

### ISSUE THREAD

**Issue by ArthurKnight** [memspace/zefyr#137]
while use 
image_picker: ^0.6.0+20
zefyr: ^0.6.0

errors become:
Because flutter_app123 depends on zefyr ^0.6.0 which depends on image_picker ^0.5.0, image_picker ^0.5.0 is required.
So, because flutter_app123 depends on image_picker ^0.6.0+20, version solving failed.
pub get failed (1)

please update the image_picker's dependence~~~~

**Comment by pulyaevskiy** [comment]
Update is on the way. Sorry for the delay.

In the meantime I can suggest forking this repo and bumping dependency versions, you can then use a temporary [dependency override](https://dart.dev/tools/pub/dependencies#dependency-overrides) in your pubspec.yaml .

**Comment by xiejibiao** [comment]
Have you solved this problem?

**Comment by pulyaevskiy** [comment]
Thank you for reporting and sorry for late response here.

I just released a new version `0.6.1` which allows to install latest version of image_picker.

Note that zefyr `0.7` will no longer depend on `image_picker` and introduce some breaking changes to `ZefyrImageDelegate`. I will have detailed documentation on these changes when `0.7` is out.
