### ISSUE TITLE
输入回显

### ISSUE THREAD

**Issue by forgetW** [memspace/zefyr#146]
## Steps to Reproduce

我用toJson.toString打印出来
[insert⟨ 嘻嘻嘻你摸摸⏎ ⟩, insert⟨ ​ ⟩ + {embed: {type: image, source: file:///storage/emulated/0/Android/data/com.zefyr.example/files/Pictures/scaled_share2qq_temp7a82fb7996eccc8ec5225fcae118209c.jpg}}, insert⟨ ⏎ ⟩]  是这个样子   回显不了啊

**Comment by pulyaevskiy** [comment]
Forgive my google translate skills, but looks like you are trying to convert Notus document to json. Please see updated quick start guide about saving and loading documents as JSON: https://zefyr-editor.gitbook.io/docs/v/v0.8.0/quick-start
