### ISSUE TITLE
I can't  use  image_picker:^0.6.1+4

### ISSUE THREAD

**Issue by kskan** [memspace/zefyr#149]
Because zefyr 0.6.0 depends on image_picker ^0.5.0 and no versions of zefyr match >0.6.0 <0.7.0, zefyr ^0.6.0 requires image_picker ^0.5.0.
So, because xxx depends on both image_picker ^0.6.1+4 and zefyr ^0.6.0, version solving failed.

**Comment by pulyaevskiy** [comment]
Closing as duplicate of #137 .
