### ISSUE TITLE
Integration with Firebase

### ISSUE THREAD

**Issue by abhee4** [memspace/zefyr#156]
Hi @pulyaevskiy 

I have an app that I am working on which is integrated with Firebase for getting the Form filled via the user and submit it to firebase.

I want to take **marked up content** from the user and want to submit that as a rich text file in firebase storage.

Can you please help me with that ?

I could not get any idea of getting it integrated with Firebase.

Thanks in advance !

r/abhee

**Comment by pulyaevskiy** [comment]
You can check out new [Quick Start](https://zefyr-editor.gitbook.io/docs/v/v0.7.0/quick-start) tutorial which I updated recently with examples of how to save and load documents. Those examples simply show how to save a document into a local file, but it should be fairly straightforward to extend these and add Firebase Storage upload step.

Look at `_loadDocument()` and `_saveDocument()` methods. Hope this helps.

**Comment by AlexMainaMunyua** [comment]
Hi @pulyaevskiy 
Regarding the issue on Integrating with firebase, are we supposed to save the document in firebase storage or firebase database.

**Comment by cgestes** [comment]
I would be you are supposed to save it in database, especially if you want
realtime collaboration.

**Comment by pulyaevskiy** [comment]
Yes, it very much depends on your needs and requirements. From Zefyr point of view it doesn’t matter where documents are saved to or loaded from. 

As far as I know you can save documents in either database and it’s really up to you to pick one that suits your needs.

**Comment by marc-walton** [comment]
> Hi @pulyaevskiy
> 
> I have an app that I am working on which is integrated with Firebase for getting the Form filled via the user and submit it to firebase.
> 
> I want to take **marked up content** from the user and want to submit that as a rich text file in firebase storage.
> 
> Can you please help me with that ?
> 
> I could not get any idea of getting it integrated with Firebase.
> 
> Thanks in advance !
> 
> r/abhee

Hey did you integrate it firebase?Can you please help me?

**Comment by abhee4** [comment]
No I did not, I dropped the idea as of now !

**Comment by adityamaurya123** [comment]
please any one tell me how i connect upload data(post) in zefyreditor in firebase database
