### ISSUE TITLE
How to clear all the contents of the editor on button tap?

### ISSUE THREAD

**Issue by ropali** [memspace/zefyr#158]
I just want to clear all the contents from the editor on a button tap. Not able to find a way to do this.

**Comment by pulyaevskiy** [comment]
You can use something like this:

```dart
void _clearDocument(ZefyrController controller) {
  controller.replaceText(0, controller.document.length - 1, '');
}
```

It would probably make sense to add a helper method to `ZefyrController` to do this though.

**Comment by ropali** [comment]
I was doing the same thing but forgot to include the -1 in the statement hence I was getting some weird errors so I though it is not the way to do this. Thanks for the help & sorry to bother you.
