### ISSUE TITLE
Implement Emojis.

### ISSUE THREAD

**Issue by shubham-cueclad** [memspace/zefyr#173]
Hello first of all wonderfull and much needed plugin developed thanks and admired.Well i am trying to include emoji's in text.
[eg: Cool Zefyr✌ Love Github❤️️ Cool Codders😎 ]

Can anyone help me for this...
Thanks in advance

**Comment by pulyaevskiy** [comment]
AFAIK, you can just use the software keyboard for (iOS, Android) to past any emojis, I believe zefyr renders them fine. Closing.
