### ISSUE TITLE
I made a separate Notus To HTML and Notus To Markdown Converter, best way to contribute?

### ISSUE THREAD

**Issue by delay** [memspace/zefyr#177]
I made some separate parsers to convert the current notus format you have to HTML and Markdown.  It takes a notus doc as input and returns an Html doc.  Same for markdown.  Not sure that its the best code, but it  works for me.

Should I release a separate package like NotusToHTML/Markdown or do you want me to contribute it to this project?  Are there plans for extensions to handle this type of feature?  

Thanks for any advice on the best way to contribute back.  Thanks for the great package!

**Comment by sil-main-coo** [comment]
It would be great if you could also do the opposite. LOL

**Comment by delay** [comment]
That would be a lot tougher if you are talking about converting random html, etc because current html can have a much greater variety of tags and can also be malformed...  Maybe there are a couple of ways to try to handle it but I don't need this feature for my use case.  How I would probably tackle it, is use a package to convert someones html to markdown, then parse the markdown to bring into notus since it has only a subset of the tags and running it through the html to markdown package the output of the markdown shouldn't have any malformed sections.

**Comment by delay** [comment]
For my own case since I am not pasting random html into notus, I can just save a copy of the notus file in my db along with a copy of html.  If the user needs to perform edits I will pull the notus doc.  If it needs to be displayed on a website I will pull the html and if the user wants it in markdown then I can generate it with the converter on the fly.

**Comment by pulyaevskiy** [comment]
I would definitely recommend to submit a PR. Note that there is a already a Markdown converter in `lib/convert.dart`, not sure if you implemented yours from scratch or made modifications to the existing one. Either way, I'll take a look and see how we can incorporate it into the package.

**Comment by delay** [comment]
Ok great I will submit a PR.

**Comment by veneno261** [comment]
did you submit a PR ?
