### ISSUE TITLE
Invalid argument error

### ISSUE THREAD

**Issue by duzenko** [memspace/zefyr#180]
I got an error when trying to load a server-generated document. There seems to be tag mismatch. I would appreciate any advice here.

## Steps to Reproduce

1. I use this json that I receive from the web site backend, supposedly generated with Zephyr
```
{"ops":[{"insert":"йцу "},{"attributes":{"bold":true},"insert":"фыв "},{"attributes":{"underline":true},"insert":"ячс "},{"insert":"екреркерв\n"}]}
```
2. Loading it like this
```
      if (_controller == null) {
        final document = NotusDocument.fromJson(jsonDecode(value)['ops']);
        _richController = ZefyrController(document);
      }
      return ZefyrEditor(
        controller: _richController,
        focusNode: _focusNode,
      );
```
3. I get this error: `Invalid argument (No attribute with key "bold" registered.): "bold"`

## Logs

```
Invalid argument (No attribute with key "bold" registered.): "bold"

User-created ancestor of the error-causing widget was: 
  Stack file:///D:/dev/pavement/lib/util/modelPage.dart:69:12
When the exception was thrown, this was the stack: 
#0      NotusAttribute._fromKeyValue (package:notus/src/document/attributes.dart:127:7)
#1      NotusStyle.fromJson.<anonymous closure> (package:notus/src/document/attributes.dart:197:33)
#2      MapMixin.map (dart:collection/maps.dart:163:28)
#3      NotusStyle.fromJson (package:notus/src/document/attributes.dart:196:25)
#4      NotusDocument._loadDocument (package:notus/src/document.dart:278:46)
```

**Comment by pulyaevskiy** [comment]
Sorry for late reply.

The document in your example definitely not a Zefyr document (there is only "b" attribute, but not "bold").

Were you able to resolve this issue?

**Comment by pulyaevskiy** [comment]
Sorry for the confusion.

Delta itself does not provide a concrete specification of any style attributes. It instead allows for implementations to define their own schema. Quill.js and Zefyr implement their own attributes and are not compatible. See Zefyr FAQ https://zefyr-editor.gitbook.io/docs/v/v0.8.0/faq .

**Comment by pulyaevskiy** [comment]
That said it should be possible to convert between the two schemas. I also have quill-compatibility in mind. Though it’d likely come in a form of converting between the two schemas again. An open question is whether it’s possible to convert preserving original semantics and without loss of information. I haven’t looked into this that much yet though.

**Comment by duzenko** [comment]
It's easier for me to fork your repo and manually replace `b` with `bold`, etc.
I fail to see value in refusing compatibility with the industry standard.
Will you consider adding an option to support quill.js? Although I doubt I can afford just sit and wait for that.

**Comment by eliasjtg** [comment]
I have the same issue :(

Implement the following components

- Flutter: Zefyr
- Angular: ngx-quill
- PHP: nadar/quill-delta-parser

And I am hardly realizing that Angular and PHP have the same semantics and are 1000% compatible, but the attributes are different in zefyr :(

Any way to get it working quickly? I am short of time

**Comment by pulyaevskiy** [comment]
I believe there is a fork of Zefyr which works with Quill.js format, so I think we can close this for now.
