### ISSUE TITLE
Compiliation issue on Mac

### ISSUE THREAD

**Issue by cc123** [memspace/zefyr#181]
Zefyr 0.8.0, Flutter 1.9

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Compiler message:
file:///Users/c/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/selection.dart:435:46: Error: Getter not found: 'kMinInteractiveDimension'.
          center: handleRect.center, radius: kMinInteractiveDimension / 2),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
file:///Users/c/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/selection.dart:435:46: Error: The getter 'kMinInteractiveDimension' isn't defined for the class '_SelectionHandleDriverState'.

 - '_SelectionHandleDriverState' is from 'package:zefyr/src/widgets/selection.dart' ('file:///Users/c/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/selection.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kMinInteractiveDimension'.
          center: handleRect.center, radius: kMinInteractiveDimension / 2),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^

Compiler failed on /Users/c/Desktop/common/lib/main.dart
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

**Comment by DannyChow-TKWW** [comment]
The same issue for me.

**Comment by TI-amit** [comment]
Facing same compiler issue in simulator and on iOS device on MAC.

file:///Users/ap/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/rich_text.dart:184:17: Error: Type 'InlineSpan' not found.
  void set text(InlineSpan value) {
                ^^^^^^^^^^
file:///Users/ap/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/rich_text.dart:184:17: Error: 'InlineSpan' isn't a type.
  void set text(InlineSpan value) {
                ^^^^^^^^^^
file:///Users/ap/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:153:18: Error: Method not found: 'ErrorSummary'.
        context: ErrorSummary('while updating editing value'),
                 ^^^^^^^^^^^^
file:///Users/amitpandey/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:153:18: Error: The method 'ErrorSummary' isn't defined for the class 'InputConnectionController'.
 - 'InputConnectionController' is from 'package:zefyr/src/widgets/input.dart' ('file:///Users/ap/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ErrorSummary'.
        context: ErrorSummary('while updating editing value'),
                 ^^^^^^^^^^^^
Compiler failed on /Users/ap/Documents/X/FlutterExercise/hello_flutter/lib/main.dart
Error launching application on iPhone Xʀ.
Exited (sigterm)

**Comment by pulyaevskiy** [comment]
This is a bit confusing. Zefyr 0.8.0 should work with Flutter 1.9. At least it did for me. Could you post here output of `flutter doctor`?

**Comment by cc123** [comment]
I think false alarm on this one. I did a full flutter upgrade, and insured Xcode/OS were up-to-date, and had no issues compiling Zefyr. Apologies for raising - I can't explain my original error message. In any case, as always great tool, and great work by all of you. Many thanks.
