### ISSUE TITLE
ZefyrRichText cursor position incorrect in Chrome

### ISSUE THREAD

**Issue by johnpryan** [memspace/zefyr#183]
Tapping a ZefyrRichText on the web doesn't always place the cursor in the right position

Steps to reproduce are:

1. load packages/zefyr/example in Chrome (`flutter config enable-web && flutter create . && flutter run -d chrome`)
2. tap the full page example and tap "edit"
3. tap the second line of a paragraph that spans multiple lines
4. observe the cursor position is incorrect

**Comment by pulyaevskiy** [comment]
Thanks for reporting!

I tried compiling Zefyr to web a month ago and noticed this as well. There was some more inconsistencies, though I was surprised it actually rendered and worked in some basic cases.

**Comment by johnpryan** [comment]
Yeah things are working nicely overall. This could likely be an issue with Flutter, but I wasn't sure exactly what the problem was.

**Comment by deisold** [comment]
@johnpryan is zefyr working for you on the web?

**Comment by johnpryan** [comment]
Yeah AFAICT.  I think I was testing on the master channel.

**Comment by pulyaevskiy** [comment]
I believe this specific issue has been addressed in the `1.0.0` branch. Closing.
