### ISSUE TITLE
[Feature Request] Allow hiding toolbar buttons

### ISSUE THREAD

**Issue by a9udn9u** [memspace/zefyr#197]
This is a feature request so I'm not using the bug report template.

I didn't find an officially supported way to hide toolbar buttons, for example, hide the bold, italic and heading buttons but show all others. What I'm doing right now is implement `ZefyrToolbarDelegate` and return a zero size widget, it hides the button but a dummy element remain in the widget tree, quite hacky.

**Comment by pulyaevskiy** [comment]
Going to close this is a duplicate of #23 . This is planned for Zefyr 1.0.
