### ISSUE TITLE
Inline toggle style (italic, bold) broken for first character

### ISSUE THREAD

**Issue by kolja-esders** [memspace/zefyr#200]
## Steps to Reproduce

1. Toggle either bold or italic style
2. Type at least one character

## Problem

The selected style gets untoggled after typing the first character and also the style was not applied to the character or any subsequent characters.

## Expected

The style should stay toggled and also the style should be applied to each typed character.

In general, the problem only appears before the first character is typed. Related to #169.

**Comment by pulyaevskiy** [comment]
This is fixed in latest release.
