### ISSUE TITLE
Bold and Italic are not applied 

### ISSUE THREAD

**Issue by minhduc1827** [memspace/zefyr#209]
## Steps to Reproduce

1. With Embed in a form samples, click description text field,the cursor focused, the keyboard showed.
2. Clicking B or I (bold/italic).it will be highlighted.
3. Entering the first character, bold or italic will be lost the highlight.
![IMG-0914](https://user-images.githubusercontent.com/4393681/69209232-07f2d000-0b89-11ea-86a1-90d5e046ba32.JPG)
![IMG-0916](https://user-images.githubusercontent.com/4393681/69209233-07f2d000-0b89-11ea-8611-5bcace7fb8b3.JPG)

**Comment by cgestes** [comment]
what version?

**Comment by cgestes** [comment]
It looks related to : https://github.com/memspace/zefyr/pull/169

**Comment by pulyaevskiy** [comment]
This is fixed in latest release.
