### ISSUE TITLE
[feature] supporting underlining text

### ISSUE THREAD

**Issue by icostel** [memspace/zefyr#212]
Would be nice to have something like:
  {
    "insert": "underlined text",
    "attributes": {
      "u": true
    }
  }

or like in GitHub markdown
  {
    "insert": "underlined text",
    "attributes": {
      "ins": true
    }
  }

<ins>underline text</ins>

**Comment by Albert-Jan** [comment]
Am I the only one wondering why support for underlining items haven't been added yet?

**Comment by icostel** [comment]
> Am I the only one wondering why support for underlining items haven't been added yet?

I guess Notus, the model parser that is used by the editor is based on the original markdown which does not support underline.

**Comment by pulyaevskiy** [comment]
This was added in 1.0.0 dev builds, thanks @Amir-P . Closing.
