### ISSUE TITLE
Flutter 1.12 support...

### ISSUE THREAD

**Issue by therichiekumar** [memspace/zefyr#214]
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by wangbo4020** [comment]
[tentative plan, click me](https://github.com/wangbo4020/zefyr/commit/cf5d5441b9b0e11e1cc109f97bc8ce0ad0ac8398)

**Comment by hatjs880328s** [comment]
> [tentative plan, click me](https://github.com/wangbo4020/zefyr/commit/cf5d5441b9b0e11e1cc109f97bc8ce0ad0ac8398)

why not create  pr ?

**Comment by jlalvarez18** [comment]
This project seems dead to me. Such a shame

**Comment by function1983** [comment]
@jlalvarez18 He already provided a fix since Nov 11. 
#210

**Comment by jlalvarez18** [comment]
@function1983 yet that PR has yet to be merged, the last commit to master has been September 23rd, and the creator does not respond to any comments or PRs.

This project is no longer being maintained by all available evidence.

**Comment by JEuler** [comment]
So, we need to fork it. :)

**Comment by pulyaevskiy** [comment]
Released zefyr 0.9 which fixes this.
