### ISSUE TITLE
Plugin doesn't run on iOS 

### ISSUE THREAD

**Issue by hkmsadek** [memspace/zefyr#216]
## Steps to Reproduce

Plugin doesn't work. it shows lots of errors

## Logs

Compiler message:
../.pub-cache/hosted/pub.dartlang.org/zefyr-0.6.1/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/services/text_input.dart:661:8: Context: 'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();
       ^^^^^^^^^^^^^^^^
../.pub-cache/hosted/pub.dartlang.org/zefyr-0.6.1/lib/src/widgets/selection.dart:425:46: Error: The getter 'kMinInteractiveSize' isn't defined for the class '_SelectionHandleDriverState'.
 - '_SelectionHandleDriverState' is from 'package:zefyr/src/widgets/selection.dart' ('../.pub-cache/hosted/pub.dartlang.org/zefyr-0.6.1/lib/src/widgets/selection.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kMinInteractiveSize'.
          center: handleRect.center, radius: kMinInteractiveSize / 2),
                                             ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.
Exited (sigterm)

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.12.13+hotfix.6 at /Users/mdzainalabedin/flutter
    • Framework revision 18cd7a3601 (5 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mdzainalabedin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 72C4D845-91E1-4CCA-A341-CB98A3265B84 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by pulyaevskiy** [comment]
Closing as duplicate. Fix released in Zefyr 0.9
