### ISSUE TITLE
The non-abstract class 'InputConnectionController' is missing implementations for these members: - TextInputClient.showAutocorrectionPromptRect

### ISSUE THREAD

**Issue by masewo** [memspace/zefyr#217]
## Steps to Reproduce

Building of my application not possible anymore while using zefyr 0.8.0 and flutter channel master (v1.13.3-pre.60) because of InputConnectionController not implementing showAutocorrectionPromptRect.

Fixed by implementing showAutocorrectionPromptRect in InputConnectionController:

https://github.com/masewo/zefyr/commit/4a8b5fdad83c2efc09877ffd124e8386d2e8b810

**Comment by sgehrman** [comment]
Same issue

**Comment by pulyaevskiy** [comment]
Pretty sure this has been addressed, closing.
