### ISSUE TITLE
ZefyrEditor is really slow to open or operate

### ISSUE THREAD

**Issue by jwehrle** [memspace/zefyr#218]
Opening a document I had previously made with ZefyrEditor now takes 30 seconds or so even while running on profile mode. Frames per second drops below 1. Nothing has changed on my end. Using branch #fix-text-input-connection-closed

**Comment by cgestes** [comment]
Any idea why?

Zefyr is pretty fast for me. I am happy to help you fix your issue if you provide a reproductible test case.

**Comment by jwehrle** [comment]
On second thought, I may have inadvertently introduced a feedback loop but I'm not sure exactly how right. I'm going to close this and deconstruct things. It's a little hard to give a reproducible example and that's probably part of the problem.

**Comment by jwehrle** [comment]
Update: Apparently I was corrupting the underlying document in some way that was causing extreme lag but did eventually parse. I still don't know what I did but rewriting the entire widget with an eye toward simplifying as much as possible eliminated the problem. Thank you for checking in with me, @cgestes

**Comment by cgestes** [comment]
👍🤘
