### ISSUE TITLE
Delta progamatically insert horizontal line

### ISSUE THREAD

**Issue by SBNTT** [memspace/zefyr#225]
Hi,

how do I insert a hr using Delta API ?

```dart
_delta.insert(" ", {
      NotusAttribute.embed.key: {"type": "hr"},
});
```
Got this error: `Embed style can only be applied to an EmbedNode`

thanks..

**Comment by pulyaevskiy** [comment]
I’d recommend to load delta into a NotusDocument and use the document to insert horizontal rule.

Curious if there is any specific reason you need to use Delta directly?

**Comment by SBNTT** [comment]
I've done that because I wrote my own HTML encoder/decoder

**Comment by shujaatak** [comment]
Try this:
```
_delta.insert(EmbedNode.kPlainTextPlaceholder, { "embed": { "type": "hr"}});
```
