### ISSUE TITLE
Error: The non-abstract class 'InputConnectionController' is missing implementations for these members

### ISSUE THREAD

**Issue by twovs** [memspace/zefyr#227]
Compiler message:
/G:/flutter/.pub-cache/hosted/pub.flutter-io.cn/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/G:/flutter/packages/flutter/lib/src/services/text_input.dart:661:8: Context: 'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();
       ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'G:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'G:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Finished with error: Gradle task assembleDebug failed with exit code 1

[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.12.13+hotfix.6 at G:\flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at G:/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = G:/Android/Sdk
    • Java binary at: G:\Android_Studio_UP\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at G:\Android_Studio_UP
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • oppo r9 plustm a • emulator-5554 • android-x86 • Android 5.1.1 (API 22)

• No issues found!
Process finished with exit code 0

**Comment by elgammalqa** [comment]
zefyr:
      git:
        url: git://github.com/memspace/zefyr.git
        ref: fix-text-input-connection-closed
        path: packages/zefyr
