### ISSUE TITLE
Ability to toggle editing features

### ISSUE THREAD

**Issue by chimon2000** [memspace/zefyr#23]
I would like the ability to disable specific features so that they cannot be selected from the editor menu, similar to what you can do with the quill editor.

**Comment by pulyaevskiy** [comment]
Just an FYI that this was on my list already. I'm not currently working on this yet though.

**Comment by congjiujiu** [comment]
you can just pass your own `ZefyrToolbarDelegate` and rewrite the `buildButton` function, you can determine which action icon to show at the toolbar, just like this:

```dart
@override
Widget buildButton(BuildContext context, ZefyrToolbarAction action, {onPressed}) {
  final icon = buttonIcons[action];

  return icon == null ? Container() : ZefyrButton.icon(
      action: action,
      icon: icon,
      onPressed: onPressed,
    );
}
```

and `buttonIcons` is your own action Map, see this [Toolbar](https://github.com/memspace/zefyr/blob/master/packages/zefyr/lib/src/widgets/toolbar.dart#L373)

**Comment by badaween-ahmed** [comment]
Any update on this? I need to remove the import image and also if possible to remove 'Hide keyboard'. This library is awesome.

**Comment by badaween-ahmed** [comment]
@congjiujiu That solution didn't work.

**Comment by YashBhalodi** [comment]
@badaween-ahmed, Yes, Zefyr is super awesome and to answer your question about 'import image button' You can do it super easily by just setting `imageDelegate` to null in `ZefyrEditor` like this.

`ZefyrEditor(
    controller: _controller, 
    imageDelegate: null,
),`

This will also disable the `take picture using the camera` though. But I think it will be you probably won't be needing that. 

In case you are wondering how did I figure this out, I just took a peek at source code. 😄 
This was in 
`  
List<Widget> _buildButtons(BuildContext context) {
    final buttons = <Widget>[
      ...
      if (editor.imageDelegate != null) ImageButton(),
    ];
    return buttons;
  }
}
`

Maybe you can find out some solution to your 'hiding the hide keyboard' button requirement if you check out the source.

**Comment by badaween-ahmed** [comment]
@YashBhalodi Wow! Thanks, man it worked. Yes I did check the source code and I provided null but I was getting exceptions because I was using the example app with the hardcoded text.

**Comment by pulyaevskiy** [comment]
Technically this has been implemented in ZefyrToolbar via several `hide***` constructor arguments. Closing this as resolved, but feel free to re-open if feel there is still something missing.
