### ISSUE TITLE
Auto capitalization

### ISSUE THREAD

**Issue by SBNTT** [memspace/zefyr#231]
```dart
TextField(
     textCapitalization: TextCapitalization.sentences,
)
```` 

Is there any easy way to implement something similar ?

**Comment by pulyaevskiy** [comment]
Zefyr already uses capitalization by sentences, but it is not customizable yet. It is definitely possible to expose this property.

Did you want to use different capitalization?

**Comment by SBNTT** [comment]
Oh, sorry you're right. My real phone was misconfigured ...
It's working as expected
