### ISSUE TITLE
Caret Position at the starting of a new line when Height is given

### ISSUE THREAD

**Issue by arxvo** [memspace/zefyr#239]
Caret Position is misaligned at the start of every new line, if "Height" is given >1 in ParagraphStyle or HeadingStyle or BlockStyle etc.

It moves to the correct position whenever anything is written.

**Comment by arxvo** [comment]
@cgestas can you please help?

**Comment by cgestes** [comment]
Hi

You can add some print (or debug) the caret.dart file. Mind the offset argument.

PS: It can be a flutter issue.

**Comment by arxvo** [comment]
Thanks it worked!
