### ISSUE TITLE
Allow read-only text to be filled in a column

### ISSUE THREAD

**Issue by xcffl** [memspace/zefyr#26]
Currently zefyr is full-screen and manage scrolling itself. However, as I want to put it in a column (to build a message stream, which looks like this issue page), I found that the ZefyrEditor widget doesn't have a size and tries to expand.
Althought I've looked into the source code, I found that it's hard to configure the selection layer to be the same size as the text which knows it size itself.

Do you have any suggestions? Or maybe this option can be added into zefyr?

**Comment by pulyaevskiy** [comment]
You could provide fixed height for ZefyrEditor, though I'm not sure if this would be exactly what you are looking for. If you need editor to shrink and expand based on the height of text then this is indeed not possible at this point. This is definitely something that can be added at some point though.

**Comment by leedstyh** [comment]
> need editor to shrink and expand based on the height of text

Hi @pulyaevskiy , Looking forward to this feature too. Need to render a list of "zefyr content" without losing their formats and styles. I think render a ZefyrEditor with `enabled: false` is a reasonable way.

**Comment by pulyaevskiy** [comment]
Hey @leedstyh, thanks for your interest! 

Feel free to thumbs up this issue. I'm trying to prioritize the most requested features first and your +1s are the main indicator I take into account.

**Comment by xcffl** [comment]
@leedstyh
I have implemented this. You may have a look at my fork https://github.com/xcffl/zefyr.
Not sure whether it's elegantly implemented or not, so I didn't make a pull request.

**Comment by pulyaevskiy** [comment]
This is now possible using `ZefyrView`. Closing.
