### ISSUE TITLE
How to customize keyboard/toolbar menu?

### ISSUE THREAD

**Issue by imikay** [memspace/zefyr#265]
How to change keyboard menu? I do not need this menu, how to change it. The first thing I can think of is to change the menu items, why that's no mention in documentation?

<img width="345" alt="image" src="https://user-images.githubusercontent.com/155487/77305637-5aa7e880-6d31-11ea-855b-7517d11a56c8.png">

**Comment by imikay** [comment]
That's an option called toolbarDelegate  in ZefyrField, set this value to your delegate, then copy _DefaultZefyrToolbarDelegate from toolbar.dart from the lib, change build method into the following or something else:

```dart
@override
  Widget buildButton(BuildContext context, ZefyrToolbarAction action,
      {VoidCallback onPressed}) {
    final theme = Theme.of(context);
    if (action == ZefyrToolbarAction.image ||
        action == ZefyrToolbarAction.cameraImage ||
        action == ZefyrToolbarAction.galleryImage) {
      final icon = kDefaultButtonIcons[action];
      final size = kSpecialIconSizes[action];
      return ZefyrButton.icon(
        action: action,
        icon: icon,
        iconSize: size,
        onPressed: onPressed,
      );
    } else {
      return SizedBox();
    }
  }
```

And set the toolbarDelegate option, like this

`toolbarDelegate: CustomZefyrToolbarDelegate(),`

I rename the _DefaultZefyrToolbarDelegate to CustomZefyrToolbarDelegate, that's it, the author really should add this to the doc, it a pity not having this in doc. 

Good lib, bad documentation. 

Current doc essentially says nothing. At least you should add how to custom toolbar in it, that's the first thing I would try to see in the doc.

**Comment by Dorbmon** [comment]
Thanks for your help.

**Comment by eliasjtg** [comment]
It is also not very optimal to 'hide' with sizedBox or Container, there should be a way to set the actions you want to use and not hardcode in this way
