### ISSUE TITLE
❗❗❗Automatically wrap after inserting the picture, and focus the cursor on a new line. What should i do???

### ISSUE THREAD

**Issue by mxismean** [memspace/zefyr#270]
When I insert a picture, the cursor of the input box is focused on the back of the picture by default.

I want to insert an image and wrap it automatically, with the cursor focused on a new line.

What should I do？ where to modify the code and what to add？

Please help me, thank you very much~
❗❗❗❗❗❗❗❗❗❗

**Comment by mxismean** [comment]
@pulyaevskiy @jolancornevin   plese help me .  Thanks very much

**Comment by CiriousJoker** [comment]
Dude we get it it's important for you, but abusing emojis to get attention makes it so people don't help you just so they don't promote this behavior.

**Comment by l86110** [comment]
notus/lib/src/heuristics/format_rules.dart
there is a method named _insertEmbed, you can custom the code like this
if (embed.type == EmbedType.image) {
      result..insert('\n');
    }

**Comment by mxismean** [comment]
> Dude we get it it's important for you, but abusing emojis to get attention makes it so people don't help you just so they don't promote this behavior.

😯😯😯

**Comment by mxismean** [comment]
> notus/lib/src/heuristics/format_rules.dart there is a method named _insertEmbed, you can custom the code like this if (embed.type == EmbedType.image) { result..insert('\n'); }

thank you 🙏
