### ISSUE TITLE
Text duplicates on writing right after dot(.)

### ISSUE THREAD

**Issue by CubeDr** [memspace/zefyr#276]
## Steps to Reproduce

1. Follow [link](https://zefyr-editor.gitbook.io/docs/quick-start) 01-03 to set up **Zefyr Editor**.
2. Launch the app and enter the editor.
![image](https://user-images.githubusercontent.com/13654700/79626649-a3a25f80-816c-11ea-9d74-bb6e4286a2a8.png)

3. Type `.` after "Start".
4. If you type text right after the `.`, connected text duplicates.
After writing `text.more.duplicates`
![image](https://user-images.githubusercontent.com/13654700/79626680-e6fcce00-816c-11ea-879b-596566b3a27d.png)

## Logs

There are no relevant logs with this issue.

**Comment by pulyaevskiy** [comment]
I wasn't able to reproduce this, closing for now, please post here if the issue reoccurs.
