### ISSUE TITLE
Save Edited text to database and retrieve it to zefyr editor 

### ISSUE THREAD

**Issue by fykid** [memspace/zefyr#28]
The format of the text that get saved in database is not as the one needed by zefyr editor?
Text that obtained onSubmit:
[insert⟨ Zefyr  ⟩, insert⟨ ⏎ ⟩ + {heading: 1}, insert⟨
Soft and gentle rich text editing for Flutter applications. ⟩ + {i: true}, insert⟨ ⏎ ⟩]

which is not valid json format.

**Comment by pulyaevskiy** [comment]
There is `NotusDocument.toJson` which returns json-serializable version of the document so you can `jsonEncode` it into a string.

`toString` returns human friendly representation mostly for debugging purposes.

**Comment by NiranjanShah** [comment]
Any solution for the above ?

**Comment by cgestes** [comment]
What issue are you referring to?

Zefyr import/export correct json already.

**Comment by ezercohen** [comment]
I couldn't find a solution here. What seems to work for me is:
`jsonEncode(doc.toJson())` when saving
and `ZefyrController(NotusDocument.fromJson(jsonDecode(JSONFromDB)))` when loading
