### ISSUE TITLE
Breaking change in latest Dart SDK update

### ISSUE THREAD

**Issue by stemuk** [memspace/zefyr#29]
After the latest Dart SDK update to `2.1.0-dev.1.0.flutter-ccb16f7282` I get the following error:
```
Because quiver_hashcode 1.0.0 requires SDK version >=1.8.0 <2.0.0 and no versions of quiver_hashcode match >1.0.0 <2.0.0, quiver_hashcode ^1.0.0 is forbidden.
So, because overwrite depends on quill_delta ^1.0.0-dev.1.0 which depends on quiver_hashcode ^1.0.0, version solving failed.
pub get failed (1)

```
It seems like a simple bump to the latest quiver_hashcode version would fix this issue.

**Comment by pulyaevskiy** [comment]
Thanks for reporting!

I've just pushed a few changes to address this. Current master should work with latest Flutter now.

**Comment by jenisonleo** [comment]
thank you @pulyaevskiy . it was so tedious to compile all dependent packages manually.

**Comment by stemuk** [comment]
Thanks for fixing this so quickly!
