### ISSUE TITLE
Hight of selection bar is different when selecting different language. 

### ISSUE THREAD

**Issue by ghost** [memspace/zefyr#292]
Hight of selection bar is different when selecting different language. 
![D3D18081-EB0A-4EE7-AFA5-C1409CC5367F](https://user-images.githubusercontent.com/48649432/81134654-fdd25b80-8f87-11ea-80c9-d75f3e80cc45.jpeg)

**Comment by cgestes** [comment]
It looks like an issue from the Flutter.

It may be related to: 
- https://github.com/flutter/flutter/issues/56308
- https://github.com/flutter/flutter/issues/40221

**Comment by pulyaevskiy** [comment]
In 1.0.0-rc.2 we have much better selection rendering, thanks mostly to Flutter itself, but also some internal fixes as well. Closing.
