### ISSUE TITLE
Zefyr storage with database 

### ISSUE THREAD

**Issue by kannel-outis** [memspace/zefyr#295]
Please about saving a zefyr document.... does it necessarily have to be saved in a JSON file or any local database would do... Please i want to start a project

**Comment by featzima** [comment]
@kannel-outis you can download a sample and see how it works.

**Comment by kannel-outis** [comment]
I have searched and I haven't seen any (still searching). I saw a lot based on JSON tho. But I was just thinking, what if it was to be stored in a database, will the styling remain the same?


And I don't even know if there's is anything like "encoding to json" in database 😂

**Comment by mossnana** [comment]
You can save in database as string.
NotusDocument ---> jsonEncode() ---> String

String documentInString = jsonEncode(_controller.document);

and When You want to show document
String---> jsonDecode() ---> NotusDocument

dynamic readyToUse = jsonDecode(documentInString);

**Comment by kannel-outis** [comment]
Ok thanks. I am going going to try that
