### ISSUE TITLE
Delta length always returning 1

### ISSUE THREAD

**Issue by edwin-alvarez** [memspace/zefyr#307]
why is this **line** always returning length == 1

how do I get the actual length of the Delta

var jsonContent = jsonDecode(content);
        var delta = Delta.fromJson(jsonContent);
        var substring = delta.slice(0, 100).concat(Delta()..insert("...\n"));
        
        **if(substring.length > 100)**
          return substring;
        else
          return delta;

**Comment by amantoux** [comment]
Length of an embedded object other than a string is always 1 in Deltas by convention

Can you explain the use case where the length of a Delta is required?

**Comment by edwin-alvarez** [comment]
what i'm trying to do is, use the 

works perfectly with this:
ZefyrView(document: NotusDocument.fromDelta(getContentFromJson("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."))),

this does not work:
ZefyrView(document: NotusDocument.fromDelta(getContentFromJson("Lorem Ipsum is simply dummy text of the printing and typesetting industry."))),

  Delta getContentFromJson(String content) {
      try {
        var jsonContent = jsonDecode(content);
        var delta = Delta.fromJson(jsonContent);
        var substring = delta.slice(0, 100);
        substring.trim();
        substring = substring.concat(Delta()..insert('...\n'));
        return substring;
      } on FormatException catch (e) {
        return Delta()..insert("$content\n");
      }
  }

It shows a empty space at the end of the line:
![image](https://user-images.githubusercontent.com/5774873/82830066-9a8e6780-9e69-11ea-95ca-641ff1620aa8.png)

then, I'm trying to find the length so I don't slide. another option is that trim actually trim all, and does not keep the space at the end

**Comment by cgestes** [comment]
what makes you think the empty space is related to the content?

It may be related to how Zefyr is rendering it? I would bet Zefyr adds a \n at the end of a document. (it is common to do that).

**Comment by edwin-alvarez** [comment]
The interesting thing is when the text is big, and I call trim then concat it get the result Iam look for.

It will be nice to have a substring function which can cut at the specified location.

**Comment by cgestes** [comment]
Can you make an example that we can run to show the issue please?

**Comment by edwin-alvarez** [comment]
I noticed my ZefyrController is adding a '\n' at the end, then I manually need to add the '\n', but, when text length is smaller than the desired substring the '\n' already exist and that's what is causing the extra '\n'

import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:zefyr/zefyr.dart';
import 'package:quill_delta/quill_delta.dart';

class ViewBookNotesScreen extends StatefulWidget {

  ViewBookNotesScreen({Key key})
      : super(key: key);

  @override
  _ViewBookNotesScreenState createState() => _ViewBookNotesScreenState();
}

class _ViewBookNotesScreenState extends State<ViewBookNotesScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
          body: _buildBody()
        );
  }

  Widget _buildBody() {
    final doc = r'''[{"insert":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\n\nLorem Ipsum "},{"insert":"\n","attributes":{"heading":3}},{"insert":"is simply dummy text of the printing and typesetting industry. "},{"insert":"Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ","attributes":{"i":true}},{"insert":"\n","attributes":{"block":"ol"}},{"insert":"Lorem Ipsum is simply dummy text of the printing and typesetting industry.","attributes":{"b":true}},{"insert":" Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, "},{"insert":"\n","attributes":{"block":"ol"}},{"insert":"Lorem Ipsum istr simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the "},{"insert":"1500s","attributes":{"b":true}},{"insert":", "},{"insert":"\n","attributes":{"block":"ol"}}]''';
    final doc2 = r'''[{"insert":"Lorem Ipsum is simply dummy text of the printing and typesetting industry.\n"}]''';

    return 
      Column(
        crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          SizedBox(height: 100,),
          ZefyrView(document: NotusDocument.fromDelta(getContentFromJson(doc2)),
          )
        ],
    );
  }

  Delta getContentFromJson(String content) {
      try {
        var jsonContent = jsonDecode(content);
        var delta = Delta.fromJson(jsonContent);
        var substring = delta.slice(0, 100);
        substring.trim();
        substring = substring.concat(Delta()..insert('...\n'));
        return substring;
      } on FormatException catch (e) {
        return Delta()..insert("$content\n");
      }
  }
}

**Comment by cgestes** [comment]
so you found your issue?

**Comment by edwin-alvarez** [comment]
well, yes, i know the issue but the initial question remains open, I need to know the length to I can remove the additional '\n' automatically added by the  Delta

**Comment by cgestes** [comment]
Ok I get it.

you know the delta.slice function returns the 100 first operations?

I guess you want the 100 first characters ?

Use NotusDocument to make your changes instead of the low level Delta?

**Comment by amantoux** [comment]
Sorry misread your initial question

delta.slice(0, 100) will return a list of Ops not a substring (taking all ops for which lengths sum up to 100) -> here it will be one op

also, unless I miss something
```getContentFromJson("Lorem Ipsum is simply dummy text of the printing and typesetting industry.")```
will cause a FormatException 
-> returning ```Delta().insert('$content\n')```

**Comment by edwin-alvarez** [comment]
@amantoux , maybe you are right but so far I see it is consistently cutting  at 100

@cgestes. NotusDocument exposes the length. now I can do what I need. 

NOTE: 

  Delta getContentFromJson(String content) {
      try {
        var jsonContent = jsonDecode(content);
        var delta = Delta.fromJson(jsonContent);
        var doc = NotusDocument.fromDelta(delta);
        
        **if(doc.length > 100) {**  

> //this is not 100 accurate because it includes the final \n. a more accurate number will be to use the doc.toPlainText().trimRight(). then get the length, but the doc.length is close enough, then, I'll use that.

          var substring = delta.slice(0, 100);
          substring.trim();
          substring = substring.concat(Delta()..insert('...\n'));
          return substring;
        }
        else {
          return delta;
        }
      
      } on FormatException catch (e) {
        return Delta()..insert("$content\n");
      }
  }

final result 
![image](https://user-images.githubusercontent.com/5774873/83029314-6b056980-9fe7-11ea-8802-33e57e08392e.png)
