### ISSUE TITLE
The getter 'offset' isn't defined for the class 'dart.core::double'.

### ISSUE THREAD

**Issue by amangautam1** [memspace/zefyr#32]
compiler message: file:///C:/Users/Aman%20gautam/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/zefyr-0.1.2/lib/src/widgets/common.dart:96:61: Error: The getter 'offset' isn't defined for the class 'dart.core::double'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'offset'.
compiler message:     double target = viewport.getOffsetToReveal(object, 0.0).offset;
compiler message:                                                             ^
compiler message: file:///C:/Users/Aman%20gautam/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/zefyr-0.1.2/lib/src/widgets/common.dart:101:54: Error: The getter 'offset' isn't defined for the class 'dart.core::double'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'offset'.
compiler message:     target = viewport.getOffsetToReveal(object, 1.0).offset;
compiler message:                                                      ^
Compiler failed on C:\flutterprojects\codelin\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 435

* What went wrong:
Execution failed for task ':app:flutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Finished with error: Gradle build failed: 1

**Comment by pulyaevskiy** [comment]
This looks like you have a very old version of Flutter itself. Please make sure to upgrade to latest beta at least.

**Comment by amangautam1** [comment]
Thanks. It is fixed now.
