### ISSUE TITLE
Centrally align text in the editor?

### ISSUE THREAD

**Issue by JacobWrenn** [memspace/zefyr#320]
Is there a way to centrally align the text in the editor?

**Comment by cgestes** [comment]
I dont think so, but it should not be too hard to implement :)

**Comment by SahajRana** [comment]
@JacobWrenn, Is this merge successful, or is there another workaround for it?

**Comment by JacobWrenn** [comment]
Hi @SahajRana, this branch on my fork has the changes on it https://github.com/JacobWrenn/zefyr/tree/centering You can add it in your pubspec to access this feature. To clarify, it provides the option for the editor text to be permanently centred - it doesn't add buttons to change the text alignment.

**Comment by SahajRana** [comment]
@JacobWrenn Oh, I'm looking to add it as a button for text alignment in editor toolbar.

**Comment by JacobWrenn** [comment]
@SahajRana, I think it would be best to open a separate issue for that. I suspect it would involve some changes to the underlying format used to store the documents.

**Comment by SahajRana** [comment]
It would be really cool if it was supported though. Well, I have already filed 2 other issues and have not got any response on them so I'm not sure if there is gonna be any help soon.
