### ISSUE TITLE
Create new type of Nodes?

### ISSUE THREAD

**Issue by fzyzcjy** [memspace/zefyr#332]
## Steps to Reproduce

Thanks for this wonderful library! I need to add new type of nodes (e.g. an embedded voice bar), but IMHO I did not find any doc about how to *create new type of nodes*... Could you please give some advice thanks!

## Logs
N/A

**Comment by cgestes** [comment]
Hi,

have a look here:
https://github.com/cgestes/zefyr/commit/e1fb1f934a9840153a49cfc513954df7b6f6f307 https://github.com/cgestes/zefyr/commit/f87b771037954085d3a391e861f9d4cb17e5c3fb

It's not very clean, but it will give you an idea of where the changes are required.

**Comment by fzyzcjy** [comment]
Thanks!
