### ISSUE TITLE
'InputConnectionController' is missing implementations for these members

### ISSUE THREAD

**Issue by edwin-alvarez** [memspace/zefyr#349]
i started getting this error, it started yesterday, after I upgrade flutter 

../../../../Shared/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.11.0/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
[        ]  - TextInputClient.currentAutofillScope
[        ]  - TextInputClient.showAutocorrectionPromptRect
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.
[        ] class InputConnectionController implements TextInputClient {
[        ]       ^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] ../../../../Shared/flutter/packages/flutter/lib/src/services/text_input.dart:790:21: Context: 'TextInputClient.currentAutofillScope' is defined here.
[        ]   AutofillScope get currentAutofillScope;
[        ]                     ^^^^^^^^^^^^^^^^^^^^
[        ] ../../../../Shared/flutter/packages/flutter/lib/src/services/text_input.dart:805:8: Context: 'TextInputClient.showAutocorrectionPromptRect' is defined here.
[        ]   void showAutocorrectionPromptRect(int start, int end);

[logs.txt](https://github.com/memspace/zefyr/files/4871096/logs.txt)

EMacPro:pioneerhelper emalware$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-3.0.pre.126, on Mac OS X 10.15.4 19E287,
    locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

• No issues found!
EMacPro:pioneerhelper emalware$

**Comment by JahsonKim** [comment]
I am facing the same issue. Any solution?

**Comment by edwin-alvarez** [comment]
As a short term, I changed my flutter channel to 'stable', but will be good if this gets a fix soon

**Comment by jheimesilveirazup** [comment]
I also changed to stable but it is not catching yet

**Comment by JahsonKim** [comment]
I changed to stable but still facing the same issue

**Comment by GyuriMajercsik** [comment]
Did you try Zefyr from master ? Basically, this would be the dependency: 

```
zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
```

**Comment by jheimesilveirazup** [comment]
Thanks, it worked
