### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by Vadaski** [memspace/zefyr#35]
compiler message: file:///C:/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/zefyr-0.1.2/lib/src/widgets/common.dart:96:61: Error: The getter 'offset' isn't defined for the class 'dart.core::double'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'offset'.
compiler message:     double target = viewport.getOffsetToReveal(object, 0.0).offset;

**Comment by pulyaevskiy** [comment]
You are likely on a very old build of Flutter SDK. Try to upgrade to at least beta 0.6 or later, this should fix it.

**Comment by Vadaski** [comment]
Thank you，I have upgraded to the latest version
