### ISSUE TITLE
When press Enter key on the keyboard on MacOS app, it won't enter new line, but to input space.

### ISSUE THREAD

**Issue by jims57** [memspace/zefyr#377]
![image](https://user-images.githubusercontent.com/1920873/88748879-b1f91200-d184-11ea-8299-616f6e477c2b.png)

**Comment by pulyaevskiy** [comment]
I've noticed this as well, when I tried it on a Mac. The issue is in macOS using different new-line character sequence than iOS.

**Comment by jims57** [comment]
@pulyaevskiy will you help fix it?

**Comment by pulyaevskiy** [comment]
This is now fixed on the master branch.
