### ISSUE TITLE
After uploading the picture, the cursor is parallel to the picture, and Chinese characters will not wrap automatically when I input them. Flashbacks also occur.

### ISSUE THREAD

**Issue by AcmeField** [memspace/zefyr#380]
When the picture is inserted and the cursor is behind the picture, when I input Chinese pinyin and have not selected Chinese characters, there will be no line feed. When I input more pinyin, the picture will be lost and occasionally the program will flash back
### Zefyr Version : 
Branch : Master 
Version : 0d69499582ee9ded8afa23b5ba3b0be8c51b7aed

### Flutter Version : 1.17.5

Looking forward to your reply.

**Comment by petchgabriel** [comment]
Do you have any solution on this problem? Thanks.

**Comment by AcmeField** [comment]
> 您对此问题有解决方案吗？谢谢。

**Comment by AcmeField** [comment]
down load source and update method   _insertEmbed.
![update_](https://user-images.githubusercontent.com/66946883/91930626-ed52a780-ed13-11ea-9b40-dc2b6951b300.jpg)

**Comment by petchgabriel** [comment]
> down load source and update method _insertEmbed.
> ![update_](https://user-images.githubusercontent.com/66946883/91930626-ed52a780-ed13-11ea-9b40-dc2b6951b300.jpg)

 @AcmeField This worked for me. Thanks for your help.
Do you have issue or bug like this ticket or not? #391

**Comment by AcmeField** [comment]
> > down load source and update method _insertEmbed.
> > ![update_](https://user-images.githubusercontent.com/66946883/91930626-ed52a780-ed13-11ea-9b40-dc2b6951b300.jpg)
> 
> @AcmeField This worked for me. Thanks for your help.
> Do you have issue or bug like this ticket or not? #391

According to my usage, the current picture problem is not able to achieve the expected effect. At present, my project time cycle is relatively tight, so I have no time to read and modify more source code. Therefore, my current solution is to disable the image upload function of this component and use the independent image upload function as compatibility.

If your project has to rely on text mixing and uploading, it may not be appropriate. In addition, I hope it can help you.

![example1](https://user-images.githubusercontent.com/66946883/92327966-fa62f400-f08f-11ea-9618-ac2866240af7.jpeg)
![example2](https://user-images.githubusercontent.com/66946883/92327968-0058d500-f090-11ea-8c04-d0214a03e1a6.jpeg)

**Comment by AcmeField** [comment]
> Do you have any solution on this problem? Thanks.

 Download the code from this master branch
, then you need to modify some of the current source code, and then use the local reference in Pubspec.YAMl

zefyr:
    path: ./zefyr

The modified file is: zefyr-> notus-> lib-> src-> heuristics -> fromat_rules.dart


fromat_rules.dart -> method : _insertEmbed


For the specific added code and location, please refer to the picture I replied to you the first time. It has details

**Comment by petchgabriel** [comment]
> > Do you have any solution on this problem? Thanks.
> 
> Download the code from this master branch
> , then you need to modify some of the current source code, and then use the local reference in Pubspec.YAMl
> 
> zefyr:
> path: ./zefyr
> 
> The modified file is: zefyr-> notus-> lib-> src-> heuristics -> fromat_rules.dart
> 
> fromat_rules.dart -> method : _insertEmbed
> 
> For the specific added code and location, please refer to the picture I replied to you the first time. It has details

Hi AcmeField,
Sorry for late reply. I just get back to work today. Thank you so much for your help and full instructions.
In my project, we need to use an embed image as a line in editor. But I will continue to find the way for solving error pasted immediately after an embed node.

If I have any solution. I will comment on my issue ticket and mention my issue ticket number in your issue as well.

Cheers.

**Comment by AcmeField** [comment]
> > > Do you have any solution on this problem? Thanks.
> > 
> > 
> > Download the code from this master branch
> > , then you need to modify some of the current source code, and then use the local reference in Pubspec.YAMl
> > zefyr:
> > path: ./zefyr
> > The modified file is: zefyr-> notus-> lib-> src-> heuristics -> fromat_rules.dart
> > fromat_rules.dart -> method : _insertEmbed
> > For the specific added code and location, please refer to the picture I replied to you the first time. It has details
> 
> Hi AcmeField,
> Sorry for late reply. I just get back to work today. Thank you so much for your help and full instructions.
> In my project, we need to use an embed image as a line in editor. But I will continue to find the way for solving error pasted immediately after an embed node.
> 
> If I have any solution. I will comment on my issue ticket and mention my issue ticket number in your issue as well.
> 
> Cheers.

Waiting for your good news . 

Cheers
