### ISSUE TITLE
Error: Too few positional arguments: 7 required, 6 given.     final toolbar = controls.buildToolbar(

### ISSUE THREAD

**Issue by hyungtaecf** [memspace/zefyr#383]
## Steps to Reproduce

1. Updated Flutter to version 1.20
2. This issue (https://github.com/memspace/zefyr/issues/275) also happened, but I fixed following the instructions there.
3. flutter run

## Logs

Launching lib\main.dart on Moto G Play in debug mode...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.11.0/lib/src/widgets/selection.dart:594:42: Error: Too few positional arguments: 7 required, 6 given.
    final toolbar = controls.buildToolbar(
                                         ^

FAILURE: Build failed with an exception.

(running on VS Code)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [versÃ£o 10.0.18362.959], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc4)
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.47.3)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by hyungtaecf** [comment]
Nevermind, it worked when I used the master version.

zefyr:
    git:
      url: git://github.com/memspace/zefyr.git
      path: packages/zefyr/
      ref: master
      commit: 9b032d8

I was using the pub one.

**Comment by harivamshi81189** [comment]
> Nevermind, it worked when I used the master version.
> 
> zefyr:
> git:
> url: git://github.com/memspace/zefyr.git
> path: packages/zefyr/
> ref: master
> commit: [9b032d8](https://github.com/memspace/zefyr/commit/9b032d8b868cf51b5eee18c74c056bfd943b8464)
> 
> I was using the pub one.

I also used the same. It worked🥳

**Comment by cgestes** [comment]
Awesome :)

Can we close?

**Comment by harivamshi81189** [comment]
> Awesome :)
> 
> Can we close?

I think yes. But, Also please update the plugin in pub.dev also.

**Comment by cgestes** [comment]
We have to wait for the maintainer.
