### ISSUE TITLE
Hope ZefyrRichText can adapt to WidgetSpan.

### ISSUE THREAD

**Issue by ahyangnb** [memspace/zefyr#386]
# Hope ZefyrRichText can adapt to WidgetSpan.

In this way, it is more convenient for other developers to change to other styles or add new features.

**Comment by cgestes** [comment]
Why would you need that?

**Comment by ahyangnb** [comment]
> Why would you need that?

Because I need to support a series of operations such as text click events, such as link triggering jump events.

**Comment by cgestes** [comment]
Did you manage to support clicking using the PRs in this project?

If yes, can we close this issue and the related one? 

Thanks

**Comment by ahyangnb** [comment]
ok
