### ISSUE TITLE
copy and paste

### ISSUE THREAD

**Issue by gedw99** [memspace/zefyr#39]
Maybe its me but on both IOS and Android Bold and Italics does not work in the sim because you cant select words or sentence, but only the whole document.

Is this a current limitation of Flutter i wonder ? Being able to access the clipboard properly i mean.

**Comment by pulyaevskiy** [comment]
To select a word you need to long-tap on that word, similarly to how regular text fields work in Flutter.
Then you can use selection handles to adjust it if needed.

Does it not work for you? It definitely works on my end.

In regards to copy/paste: Flutter only supports plain text in the Clipboard at this point so copying to clipboard does not preserve styles, unfortunately.

This is something I was planning to address, either by contributing to Flutter or rolling custom clipboard interactions with native side in Zefyr.

**Comment by gedw99** [comment]
Hmm.. Thats what i was doing, but the copy / paste UI handles were not showing up.
I will try again as its been a while.

**Comment by gedw99** [comment]
@pulyaevskiy It works for me on IOS and Android. Must have been having a bad day when i raised this :)

closing... thanks again
