### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Dorbmon** [memspace/zefyr#393]
/D:/flutter/.pub-cache/git/zefyr-0d69499582ee9ded8afa23b5ba3b0be8c51b7aed/packages/zefyr/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.performPrivateCommand
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or

[√] Flutter (Channel master, 1.22.0-2.0.pre.129, on Microsoft Windows [Version 10.0.19041.450], locale zh-CN)
    • Flutter version 1.22.0-2.0.pre.129 at D:\flutter
    • Framework revision 1d7838a8f0 (6 hours ago), 2020-08-29 02:03:03 -0400
    • Engine revision 3029dcd93e
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

**Comment by pulyaevskiy** [comment]
If you're on Flutter master channel you must use master branch of Zefyr repo as well.
