### ISSUE TITLE
ZefyrEditor Not Scrollable until tapped 

### ISSUE THREAD

**Issue by ArjanAswal** [memspace/zefyr#396]
### ZefyrEditor (when in view mode) is Not Scrollable until the widget is tapped. 

When the text gets big enough for the screen size to contain, the Zefyr Editor widget should become scrollable but it does not, when scrolled down it just quickly gets back to the initial position.

However, when I tap at the Editor widget it works just right. 

![ezgif-7-a83477ff5514](https://user-images.githubusercontent.com/64231789/91723358-435f0800-ebb9-11ea-95d3-ea242bdc9385.gif)

## Code:
```
Scaffold(
      backgroundColor: Theme.of(context).backgroundColor,
      body: controller == null
          ? Center(
              child: CircularProgressIndicator(),
            )
          : ZefyrScaffold(
              child: ZefyrTheme(
                data: theme,
                child: ZefyrEditor(
                  autofocus: false,
                  controller: controller,
                  focusNode: focusNode,
                  mode: ZefyrMode.view,
                  imageDelegate: MyZefyrImageDelegate(),
                  padding:
                      MediaQuery.of(context).orientation == Orientation.portrait
                          ? EdgeInsets.symmetric(vertical: 40, horizontal: 20)
                          : EdgeInsets.symmetric(vertical: 5, horizontal: 20),
                ),
              ),
            ),
    );
```

**Comment by devakrishna33** [comment]
Why is this issue closed? was this solved? Facing a similar problem

**Comment by ArjanAswal** [comment]
Actually the issue was not related to the Zeyfr package. 
The App was rebuilding infinite times because of the provider package.
If you are facing the same issue and using provider for state management try checking if any widget keeps on rebuilding and set listen to false.

**Comment by devakrishna33** [comment]
Yeah, that solved it, for me the issue was I was using uniqueKey at a place which was causing flutter to run multiple times, in case anyone faces similar issue.
