### ISSUE TITLE
Text-filled screen causes the inability to continue typing. 

### ISSUE THREAD

**Issue by Lenzeg** [memspace/zefyr#407]
My app "Minimalist Journal" uses this package, so thank you for that. However, I got some users complaining about a jittery screen when typing in the last sentence. I uploaded some gifs, but maybe it doesn't show it correctly. You can download my app and try it (i'll give you refund for the 0.49 EUR if you don't want to spend).
 (see gifs below):

![ezgif com-gif-maker](https://user-images.githubusercontent.com/22194474/94000855-050fcf80-fd98-11ea-869a-9d22a9178380.gif)

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/22194474/94001125-5cae3b00-fd98-11ea-8b15-fc378eeaa551.gif)

Thanks in advance, I hope this can get fixed!

**Comment by urovoros** [comment]
I have the same problem.
When editing text, the screen seems to move to the top and bottom.

**Comment by pulyaevskiy** [comment]
This should be fixed in 1.0-dev version. Unfortunately fixing this in 0.x wouldn't be a trivial task. I'd encourage at least experimenting with 1.0-dev to see if it's on par for you with 0.x versions and reporting any issues (especially blocking) back. Thanks. Closing this.
