### ISSUE TITLE
How can I insert a image in version 1.0, has the feature been removed?

### ISSUE THREAD

**Issue by HUA616436641** [memspace/zefyr#421]
## Steps to Reproduce

1. update to [1.0-dev]
2. run example

## Logs
pickImage button could not found

**Comment by HUA616436641** [comment]
![image](https://user-images.githubusercontent.com/17864476/95649606-cc4e5500-0b10-11eb-854f-e429f8b13139.png)
em,I found the result in source..

**Comment by yeelone** [comment]
Can I ask how to display the image picker button? just upgrade to 1.0。thanks

**Comment by pulyaevskiy** [comment]
Yeah there is no built in button for images nor any widgets.

I'm still to write docs on how to work with images or any other embeds.

First thing is, as mentioned above, you must provide your own embedBuilder function which is capable of building image widgets based on your requirements.

As of toolbar buttons, you can use the default constructor of ZefyrToolbar to pass any set of children buttons, so nothing is limited there, yet at least. It'd probably be a good idea to just copy the default layout from ZefyrToolbar.basic and add your buttons as needed.

**Comment by yeelone** [comment]
> Yeah there is no built in button for images nor any widgets.
> 
> I'm still to write docs on how to work with images or any other embeds.
> 
> First thing is, as mentioned above, you must provide your own embedBuilder function which is capable of building image widgets based on your requirements.
> 
> As of toolbar buttons, you can use the default constructor of ZefyrToolbar to pass any set of children buttons, so nothing is limited there, yet at least. It'd probably be a good idea to just copy the default layout from ZefyrToolbar.basic and add your buttons as needed.

Hi,  Would you please tell me how to implements the EmbedBuilder function? 

Here is the code I wrote in version 0.11 
`Widget customZefyrEmbedBuilder(BuildContext context, EmbedNode node) {
    ImageSource  gallerySource = ImageSource.gallery;
  
    final image = pickImage(gallerySource);
    return Container(
      width: MediaQuery.of(context).size.width,
      child: GestureDetector(
        child: Image.network(
                image,
                fit: BoxFit.contain
            ),
        onTap: () {
          Navigator.push(context, MaterialPageRoute(builder: (_) {
            return FullScreen(image);
          }));
        },
      ),
    );
}`

**Comment by pulyaevskiy** [comment]
It's going to be a bit more involved than it used to be in 0.x. I'll try to create a demo in the example app in the next couple of days. Stay tuned.

**Comment by yeelone** [comment]
> It's going to be a bit more involved than it used to be in 0.x. I'll try to create a demo in the example app in the next couple of days. Stay tuned.

Thank you very much . I just figure it out.  here is the code 
`class CustomInsertImageButton extends StatelessWidget {
  final ZefyrController controller;
  final IconData icon;

  const CustomInsertImageButton({
    Key key,
    @required this.controller,
    @required this.icon,
  }) : super(key: key);

  Future<String> upload(File imageFile) async {    
      // open a bytestream
      var stream = http.ByteStream(DelegatingStream.typed(imageFile.openRead()));
      // get file length
      var length = await imageFile.length();

      // string to uri
      var uri = Uri.parse(server + "/upload");

      // create multipart request
      var request = http.MultipartRequest("POST", uri);

      // multipart that takes file
      var multipartFile = http.MultipartFile('note', stream, length,
          filename: basename(imageFile.path));

      // add file to multipart
      request.files.add(multipartFile);

      // send
      var response = await request.send();
      // listen for response.join()
      return response.stream.transform(utf8.decoder).join();
    }
  
  Future<String> pickImage(ImageSource source) async {
      final file = await ImagePicker.pickImage(source: source,imageQuality: 65);
      if (file == null) return null;
      String value =  await upload(file);
      var v = jsonDecode(value);
      var url = server + "/" + v["data"]["filepath"];
      print(url);
      return url;
    }

  @override
  Widget build(BuildContext context) {
    return ZIconButton(
      highlightElevation: 0,
      hoverElevation: 0,
      size: 32,
      icon: Icon(
        icon,
        size: 18,
        color: Theme.of(context).iconTheme.color,
      ),
      fillColor: Theme.of(context).canvasColor,
      onPressed: () {
        final index = controller.selection.baseOffset;
        final length = controller.selection.extentOffset - index;
        ImageSource  gallerySource = ImageSource.gallery;
        // controller.replaceText(index, length, BlockEmbed.image("https://img.alicdn.com/imgextra/i1/6000000003634/O1CN01XkL17h1ciPvkUalkW_!!6000000003634-2-octopus.png",));
        final image = pickImage(gallerySource);
        image.then((value) => {
          controller.replaceText(index, length, BlockEmbed(value) )
        } );
      },
    );
  }
}`

**Comment by Saibaba-Alapati** [comment]
Do we need to import any thing to use Block embed i am not able to use it  and also what is ZIconbutton  is that a custom button  defined?

**Comment by hyouuu** [comment]
@yeelone does the GestureDetector work for your image widget? It doesn't respond to tap in my case
