### ISSUE TITLE
Suggestion: Add maxLines, onChanged and hintText properties to ZefyrEditor

### ISSUE THREAD

**Issue by HrX03** [memspace/zefyr#428]
I need both of these for my notes app, maxLines to display the editor inside a small card, cuz i dont want it to become too tall. onChanged i need to store content on db on save. hintText cuz else by default it shows an empty space with no hints

**Comment by pulyaevskiy** [comment]
`maxLines` is not going to work with Zefyr unfortunately, however in 1.0-dev version I've already added `minHeight` and `maxHeight` which should cover this use case.

The `onChanged` event can be simulated by listening on the `NotusDocument.changes` stream.
And `hintText` can be set in `ZefyrField` decoration.

**Comment by HrX03** [comment]
Aight, thanks for the tips! Btw, found a bug where hint doesnt disappear when you activate code or quote style. I also found why it happens, basically in ZefyrField the isEmpty param is true only if the document is empty, tho it should be considered empty if either quote or code isnt enabled.

**Comment by pulyaevskiy** [comment]
Thanks @HrX03 , could you file a separate issue for the bug you found? This way I won't forget to fix it, or someone else can pick it up and submit a PR. Thanks.

Closing this issue as resolved.
