### ISSUE TITLE
Is there any widget in 1.0-dev equivalent to ZefyrView

### ISSUE THREAD

**Issue by sridattayalla** [memspace/zefyr#434]
It is very straightforward to use `ZefyrView` when we just want to display the delta content. But I can't find any such direct way in 1.0-dev (I know there is viewonly mode in ZefyrEditor). Are there any plans to implement such thing in future?

**Comment by pulyaevskiy** [comment]
You can use combination of `showCursor`, `readOnly` and `enableInteractiveSelection` to control interactive aspects of the editor. These properties now match with Flutter's standard `TextField`.

To get a similar experience with `ZefyrView` you'll need to use:

```dart
return ZefyrEditor(
  showCursor: false,
  readOnly: true,
  enableInteractiveSelection: false,
);
```

**Comment by pulyaevskiy** [comment]
I'm going to close this is resolved, but feel free to re-open if there is more questions. Make sure to run the new example app in zefyr package, it now includes several demos showcasing different usage scenarios.
