### ISSUE TITLE
Copy in Read Mode

### ISSUE THREAD

**Issue by xcffl** [memspace/zefyr#44]
It seems that copy doesn't work in read mode.

Looking into the code I find that the selection layer disapprars in read mode. I'm not sure it is a bug or intended behavior?

**Comment by pulyaevskiy** [comment]
Good question. I'd say current behavior is by design, however I see your point and there should be a way to allow selection in read mode.

I'll mark this as a feature request.

**Comment by pulyaevskiy** [comment]
This is now possible by setting `ZefyrEditor.mode` to `ZefyrMode.select` (since 0.7.0). Closing.
