### ISSUE TITLE
Help on dynamic insert and OnChange event

### ISSUE THREAD

**Issue by LearningRaph** [memspace/zefyr#444]
Hi,

sorry for this is not a bug report but I need help as the documentation is scarce. I would like to dynamically insert text to the document and listen to document change to activate widget callback. Here is my code. The _loadDocument is working, but _addToDocument is not (ocr result) and I don't know how to call _getDocument on document change...

`class SmartEditorState extends State<SmartEditor> {
  ZefyrController _controller;
  FocusNode _focusNode;

  @override
  void initState() {
    super.initState();
    _loadDocument('');
    _focusNode = FocusNode();
  }

  @override
  void dispose() {
    _controller.dispose();
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ZefyrScaffold(
      child: ZefyrTheme(
        child: ZefyrEditor(
          controller: _controller,
          focusNode: _focusNode,
        ),
      ),
    );
  }

  void _loadDocument(data) {
    Delta delta = Delta()..insert(data + '\n');
    NotusDocument document = NotusDocument.fromDelta(delta);
    _controller = ZefyrController(document);
  }

  void _addToDocument(data) {
    // _controller.document.toDelta()..insert(data + '\n');
    Delta delta = _controller.document.toDelta()..insert(data + '\n');
    NotusDocument document = NotusDocument.fromDelta(delta);
    _controller = ZefyrController(document);
  }

  void _getDocument() {
    widget.callback(_controller.document);
  }
}`

Thanks for your help !

**Comment by LearningRaph** [comment]
To help others, I found how to attach a onChange event like this to write in the initState function : 

`_controller.document.changes.listen(
      (NotusChange change) {
        widget.callback(_controller.document);
      },
    );`


For inserting I found this, but it inserts at the begining of document instead of the end...

`     void _addToDocument(data) {
    Delta delta = Delta()..insert(data + '\n');
    _controller.compose(delta);
  }
`

Hope it helps

**Comment by cgestes** [comment]
Hi,

You can use Delta.retain to skip to the position you want.

(Sorry on the phone, it's difficult to give an exemple)

**Comment by LearningRaph** [comment]
well I'm in for an example when you are back home :) Thanks !

**Comment by LearningRaph** [comment]
@cgestes if you could give me an example I'm still interested in it. Thank you :)

**Comment by cgestes** [comment]
Sorry, I missed your previous message.

to insert at the end try something along the line: (you may need to remove 1 or add 1 to the length, but should do without)

```
void _addToDocument(data) { 
Delta delta = Delta()
    ..retain(_controller.document.length)
    ..insert(data + '\n'); 
_controller.compose(delta); 
}
```

**Comment by LearningRaph** [comment]
Yep, had to remove 1 but it works perfectly.

Thanks for the example. Hope it helps others :)
