### ISSUE TITLE
compose image attribute into NotusDocument lose image information

### ISSUE THREAD

**Issue by ttlg** [memspace/zefyr#45]
Hi, 
I am not sure this is bug or spec. 
But when I tried to compose embed image attribute into NotusDocument,  the image information was lost. 

Here is the code I wrote.
``` dart
 test('compose embed image', () {
      final imageDelta = Delta.fromJson([
        {
          "insert": "",
          "attributes": {
            "embed": {"type": "image", "source": "http://img.jpg"},
          }
        }
      ])
      ..insert('\n');
      final doc = NotusDocument();
      doc.compose(imageDelta, ChangeSource.local);
      expect(doc.toDelta(), imageDelta);
});
```
```
  Expected: Delta:<insert⟨  ⟩ + {embed: {type: image, source: http://img.jpg}}
            insert⟨ ⏎ ⟩>
    Actual: Delta:<insert⟨ ⏎⏎ ⟩>
```

**Comment by pulyaevskiy** [comment]
Good question. There are a few things here.

First, I'd advise not to use `compose()` method unless you're absolutely sure what you are doing is correct. Especially if you need to apply a local change. See dartdoc for `NotusDocument.compose` for more details.

Second, your `imageDelta` is not a valid image embed, this is why you don't see it in the result. This is another reason I do not recommend using `compose`. Normally you should never try to compose hand-written Deltas into Notus documents. You risk corrupting the document state this way.

A better (and recommended) way to apply changes to a document is using all the other methods on `NotusDocument`. So for your case:

```dart
final doc = NotusDocument();
final delta = doc.format(0, 0, NotusAttribute.embed.image('http://img.jpg'));
// format() method returns actual Delta composed into this document, 
// so you can observe it if needed
print(delta);
```

Hope this helps.

**Comment by ttlg** [comment]
Thank you for your explanation!
I understood right way to apply changes to NotusDocument, also why my code failed. 
I needed zero width space (8203) for insert.
