### ISSUE TITLE
Quill delta formats are different

### ISSUE THREAD

**Issue by oriollpz** [memspace/zefyr#453]
I am using Zefyr text editor in my Flutter mobile app. This editor transforms the data to a Delta Quill format, or at least that's what they say.

When I load this content in a QuillJS Angular widget, it doesn't work because of bad formatting. The Zefyr editor saves an Array, while the actual Delta JSON format should be an Object. But most important, Zefyr uses different names for the objects in reference of the type texts the editor is using.

Therefore, I can't use Zefyr in my Flutter app and QuillJS in my Angular app even though they say they are using the same format. It is similar, but not the same.

Am I missing something? Is someone using Zefyr and QuillJS editor as I am doing?

Example error:
`Invalid argument (No attribute with key "code-block" registered.): "code-block"`

Thanks!

**Comment by pulyaevskiy** [comment]
Please see FAQ: https://github.com/memspace/zefyr/blob/master/doc/faq.md

Short answer is - Zefyr documents are not compatible with Quill.js editor.

**Comment by oriollpz** [comment]
> Please see FAQ: https://github.com/memspace/zefyr/blob/master/doc/faq.md
> 
> Short answer is - Zefyr documents are not compatible with Quill.js editor.

Thanks for the quick answer, therefore, what can I use in Angular to understand Notus formats?

**Comment by diegogarciar** [comment]
Can it be manually converted?
