### ISSUE TITLE
NotusAttributeBuilder The class 'NotusAttributeBuilder<String>' doesn't have a constructor named '_'.

### ISSUE THREAD

**Issue by MuhmdHsn313** [memspace/zefyr#455]
## Create custom `NotusAttributeBuilder`

I tried to create a new `NotusAttributeBuilder` by extends it and create my own. But it throws this error (because of the private constructor):
```
The class 'NotusAttributeBuilder<String>' doesn't have a constructor named '_'.
```
My code:

```dart
class GiphyNotusAttribute extends NotusAttributeBuilder<String> {
  static const _kGiphy = 'giphy';

  const GiphyNotusAttribute._() : super._(_kGiphy, NotusAttributeScope.line);

  NotusAttribute<String> get gif => NotusAttribute<String>._(key, scope, 'gif');
}
```
I'm also tried using `export` for `attributes.dart` on my new dart file, I thought it'll enable me to use the private constructor but it also throws the same error.

```dart
export 'package:notus/src/document/attributes.dart';

class GiphyNotusAttribute extends NotusAttributeBuilder<String> {
  static const _kGiphy = 'giphy';

  const GiphyNotusAttribute._() : super._(_kGiphy, NotusAttributeScope.line);

  NotusAttribute<String> get gif => NotusAttribute<String>._(key, scope, 'gif');
}
```
Should I fork the GitHub project or not?
Thanks...

**Comment by pulyaevskiy** [comment]
Yes, notus attributes are only meant to be defined internally in notus package, you'd have to fork the repo to add yours.
