### ISSUE TITLE
Not compatible with Notus

### ISSUE THREAD

**Issue by T-Shamspour** [memspace/zefyr#457]
Got below error when did flutter pub get

Because every version of notustohtml depends on notus ^0.1.5 and zefyr 1.0.0-dev.2.0 depends on notus ^1.0.0-dev, notustohtml is incompatible with zefyr 1.0.0-dev.2.0.

And because no versions of zefyr match >1.0.0-dev.2.0 <2.0.0, notustohtml is incompatible with zefyr ^1.0.0-dev.2.0.

So, because **** depends on both zefyr ^1.0.0-dev.2.0 and notustohtml ^0.0.8, version solving failed.
pub get failed (1; So, because **** depends on both zefyr ^1.0.0-dev.2.0 and notustohtml ^0.0.8, version solving failed.)

**Comment by JacobWrenn** [comment]
Have a look at the latest version of notustohtml, `0.0.9-dev.2.0`. It should be fully compatible with the latest zefyr.

**Comment by pulyaevskiy** [comment]
Sounds like this is not specific to Zefyr itself. Closing.
