### ISSUE TITLE
No action bar

### ISSUE THREAD

**Issue by stoneLee81** [memspace/zefyr#461]
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (8 days ago) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)

flutter web

Run the demo using flutter web, and found that there is no actionbar, as shown in the figure

![image](https://user-images.githubusercontent.com/18001708/103072851-621e5a00-4601-11eb-93ae-152c3824dc45.png)

This problem is also true under the app

**Comment by bluesky2091** [comment]
I have encountered the same issue . Could anyone help take a look?

**Comment by GyuriMajercsik** [comment]
It seems that a bug or naming mistake was introduced recently. 

You can create the action bar (`ZefyrToolbar`) using below code. I'm sure this will be fixed in later changes. 

```
ZefyrToolbar.basic(
    controller: _zefyrController,
    hideBoldButton: true,
    hideCodeBlock: true,
    hideHeadingStyle: true,
    hideItalicButton: true,
    hideLink: true,
    hideListBullets: true,
    hideListNumbers: true,
    hideQuote: true,
    hideStrikeThrough: true,
    hideUnderLineButton: true,
),
```

**Comment by GyuriMajercsik** [comment]
This happens due to this change: https://github.com/memspace/zefyr/commit/b719dd5db6c44ddaa73b965c398a1fc96ea25229
