### ISSUE TITLE
How to implement Image attachment in zefyr 1.0.0-dev.2.0

### ISSUE THREAD

**Issue by priyeshstackapp** [memspace/zefyr#463]
Thank you for making this dependency with flutter web support and very useful for my project.

Can you please help me with **How to implement Image attachment in zefyr 1.0.0-dev.2.0** ?

Because i can not find any proper code related to it. Thank you.

**Comment by singerdmx** [comment]
I used ImagePicker https://pub.dev/packages/image_picker 
Here is how I implemented it:

https://github.com/singerdmx/flutter-quill/blob/master/lib/widgets/toolbar.dart#L419

Hope this helps

**Comment by priyeshstackapp** [comment]
Thank you for sharing your project as reference. Now i'm having my own function to pick and upload image. 🥇
