### ISSUE TITLE
Feature request: support custom typefaces.

### ISSUE THREAD

**Issue by JediBurrell** [memspace/zefyr#47]

**Comment by pulyaevskiy** [comment]
Thanks for submitting.

Currently you should be able to set custom typefaces by configuring your own [DefaultTextStyle](https://docs.flutter.io/flutter/widgets/DefaultTextStyle-class.html). Something like this:

```dart
  Widget build(BuildContext context) {
    final style = TextStyle(fontFamily: 'Open Sans');
    return DefaultTextStyle.merge(
      style: style,
      child: ZefyrEditor(/* ... */),
    );
  }
```
