### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mehrdad-shokri** [memspace/zefyr#475]
Hi, the text editor already supports rtl. But components like _NumberPoint, _BulletPoint should draw numbers/points on right if the corresponding text is rtl. I tried changing the appending order in ``editable_text_line.dart`` ``mount`` method like this:  
```
  @override
  void mount(Element parent, dynamic newSlot) {
    if (isLtr(context)) {
      _mountChild(widget.leading, TextLineSlot.leading);
      _mountChild(widget.body, TextLineSlot.body);
    } else {
      _mountChild(widget.body, TextLineSlot.body);
      _mountChild(widget.leading, TextLineSlot.leading);
    }
  }
```
But was not successful(I passed BuildContext from parent widget when building this one, the error I got was: ``Failed assertion: line 3341 pos 12: 'parent == null ||
I/flutter ( 5038): parent._lifecycleState == _ElementLifecycle.active': is not true.`` )  

If you point me in right direction I can send a PR

**Comment by pulyaevskiy** [comment]
@Amir-P wondering if you can weigh in here? Specifically:

> But components like _NumberPoint, _BulletPoint should draw numbers/points on right if the corresponding text is rtl

I believe this still needs to be addressed?

**Comment by pulyaevskiy** [comment]
Actually, nevermind, just tested and it appears that the leading widget in lists does take into account Directionality now, thanks to @Amir-P work.

Closing.
