### ISSUE TITLE
Error: No named parameter with the name 'nullOk' in text_line.dart:44:47

### ISSUE THREAD

**Issue by Solidara** [memspace/zefyr#477]
I just upgraded to new flutter dev version and getting the following error with zefyr now, when starting my app:

**zefyr-1.0.0-dev.2.0/lib/src/widgets/text_line.dart:44:47: Error: No named parameter with the name 'nullOk'.
      locale: Localizations.localeOf(context, nullOk: true),**

[✓] Flutter (Channel beta, 1.26.0-17.3.pre, on Linux, locale de_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)

**Comment by m-j-g** [comment]
Yeah, the new release in the beta channel broke it.  I have the same problem

**Comment by singerdmx** [comment]
Possibly the fix is this? https://github.com/singerdmx/flutter-quill/commit/88014d73cd67e7205b49617cf4ba4fecf224d249

**Comment by jason-downs** [comment]
This is an issue in the recent version of futter master channel, which we have to use because we're building a flutter desktop app. This error prevents the app from running and there isn't a suitable substitute for the zefyr for what I'm doing at the moment. (I'm using the zefyr prerelease version since that has better desktop app support.)

**Comment by singerdmx** [comment]
What is flutter desktop?
Do you mean web?

**Comment by jason-downs** [comment]
> What is flutter desktop?
> Do you mean web?

No, I mean a macOS/windows/linux app: 
https://flutter.dev/desktop

**Comment by AldanisVigo** [comment]
Workaround, just remove the nullOk: true. It compiled for me.

**Comment by axgalache** [comment]
Hello @AldanisVigo 
I'm trying to edit the file for removing nullOk: true , but I can not locate and open the file
../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/text_line.dart:44:47
Do you know where I can find this file? I'm on Mac OS Big Sur (m1)

**Comment by singerdmx** [comment]
@axgalache 

This repo has been inactive for months.  See https://github.com/memspace/zefyr/issues/409#issuecomment-790671992

Just FYI to save your time here.

**Comment by featzima** [comment]
Please try [Zefyrka package](https://pub.dev/packages/zefyrka) instead of this one. 

Zefyrka is a fork of Zefyr package with the following improvements:
- support of Flutter 2.0
- opt-in the null safety
- text color
- background color
- paragraph alignment
- paragraph indentation

**Comment by pulyaevskiy** [comment]
Dev builds are expected to have breaking changes, so yeah the fix was to remove the extra argument.

Please see zefyr `1.0.0-rc.1` for latest updates and fixes.
