### ISSUE TITLE
Feature request: support keyboard shortcuts.

### ISSUE THREAD

**Issue by JediBurrell** [memspace/zefyr#48]
Here are the common keyboard shortcuts for manipulating text:

Ctrl+Z: Undo.  
Ctrl+Shift+Z/Ctrl+Y: Redo.  
Ctrl+Backspace: Delete last word.  
Shift+Left/Right: Select, move selection to left/right.  
Ctrl+A: Select all.

**Comment by pulyaevskiy** [comment]
This is definitely a must have.

As far as I know there are some limitations on the Flutter side, e.g. we don't have access to key press events in TextInput plugin. So this would require some research. Hopefully with Flutter desktop embedding getting more progress we'll see some support for this.

Let me know if you know of any other way of achieving this.

**Comment by gedw99** [comment]
@pulyaevskiy This is a golang based Flutter Desktop. It has keyboard shortcuts

https://github.com/Drakirus/go-flutter-desktop-embedder

Also its pure golang and does not need alot of the extra layers like the Flutter Desktop Embedder.
Each to his own as they say, but i prefer the golang approach.

Anyway it has keyboard shortcut access and so it should be easy to wire up zefyr key board events into it. If i can help just holler...

**Comment by pulyaevskiy** [comment]
@gedw99 Thanks. I'm following this project as well and it looks very promising.

Though the way I understand this issue is that it's about supporting keyboard shortcuts for Android/iOS, e.g. when running Flutter app on a tablet with attached keyboard. For this we need Flutter engine itself to support keyboard shortcuts.

Please, correct me if I'm wrong.

**Comment by JediBurrell** [comment]
@pulyaevskiy 

It would need to use the built-in `RawKeyboardListener`. I'll look more into it, unfortunately Flutter doesn't currently have a proper built-in way to check for functional keys (like `isControlDown`), so it'd all have to be done with the `metaState`.

It primarily affects Chromebooks which (typically) always have a keyboard connected to it.

**Comment by gedw99** [comment]
i think RawKeyboardListener is the way to go also...

**Comment by pulyaevskiy** [comment]
Ok, this should be doable. It worth noting that raw key events are not supported on iOS, unfortunately (only Android and Fuchsia according to docs).
I might need to get a device with physical keyboard as well to implement this, but that's solvable too.

**Comment by gedw99** [comment]
Get a cheapie Chromebook.
That's how I tested it.

The other think you immediately notice when running your Android app on chrome OS is the ESC key is back and it's really as intuitive way to work fast. But the TAB key allows you to jump forward through items on the screen.

Btw there is a chrome OS emulator for Android studio  works well and is fast and your key board binding should work.

Try that ...

**Comment by pulyaevskiy** [comment]
Zefyr 1.0.0-rc.1 comes with keyboard shortcuts. I'm closing this issue as it's about generic support for keyboard. Please submit separate issues for any specific shortcuts you're missing.
