### ISSUE TITLE
too few positional arguments error when building 0.12.0

### ISSUE THREAD

**Issue by jabari-pulliam** [memspace/zefyr#483]
## Steps to Reproduce

Using this pubspec:
`dependencies:
  zefyr: ^0.12.0
  quill_delta: ^1.0.0`

Using this code:
`class NoteEditor extends StatefulWidget {
  @override
  State createState() => _NoteEditorState();
}

class _NoteEditorState extends State<NoteEditor> {
  ZefyrController _controller;
  FocusNode _focusNode;

  @override
  void initState() {
    super.initState();

    final document = _loadDocument();
    _controller = ZefyrController(document);
    _focusNode = FocusNode();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Note'),
      ),
      body: ZefyrScaffold(
        child: ZefyrEditor(
          padding: EdgeInsets.all(10),
          controller: _controller,
          focusNode: _focusNode,
        ),
      )
    );
  }

  NotusDocument _loadDocument() {
    final delta = Delta()..insert('Hello\n');
    return NotusDocument.fromDelta(delta);
  }
}`

## Logs

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../../sdks/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.12.0/lib/src/widgets/selection.dart:659:42: Error: Too few positional arguments: 8 required, 7 given.
    final toolbar = controls.buildToolbar(
                                         ^

```
```

`
[✓] Flutter (Channel beta, 1.26.0-17.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.2.pre at /home/jabari/development/sdks/flutter
    • Framework revision 79b49b9e10 (6 days ago), 2021-02-03 15:33:39 -0800
    • Engine revision 2c527d6c7e
    • Dart version 2.12.0 (build 2.12.0-259.8.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jabari/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /home/jabari/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /home/jabari/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at /home/jabari/applications/idea-IU-203.6682.168
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.
`

**Comment by jabari-pulliam** [comment]
Update: I had the same problem with flutter_quill and ultimately found that a recent update of flutter broke everything. I ended up downgrading flutter and it resolved the issue, as per: https://github.com/flutter/flutter/issues/75172.

**Comment by singerdmx** [comment]
Which flutter channel are you using?

**Comment by singerdmx** [comment]
I believe it is the diff between master and stable.
Check out https://github.com/singerdmx/flutter-quill/pull/19/files
We are using two branches now.
Default branch master is on channel master. To use channel stable, switch to branch stable. Branch master on channel master supports web.

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/107568918-8b3c7f00-6b9c-11eb-914e-5994c00e11bd.png)


https://viveky259259.medium.com/master-and-stable-channel-in-flutter-at-a-time-b6bdd044e608

**Comment by jabari-pulliam** [comment]
> Which flutter channel are you using?

I am using the beta channel of flutter. 

After the downgrade: 
`[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-18.1.pre at /home/jabari/development/sdks/flutter
    • Framework revision 198df796aa (4 months ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)`

**Comment by singerdmx** [comment]
No wonder. You can not expect the code to work with channel beta. 
This is not an issue for the repo at all

**Comment by jwehrle** [comment]
So I ran into this same problem while in Channel stable after updating to Flutter 2. The simplest "solution" was to copy the zefyr, notus, quill_delta, and quiver_hashcode files to a folder under lib and fix the original error (add a null parameter to the function call). In the next few days I will analyze the code and make sure I'm happy with it but for now this is no longer a bug that breaks my app.

**Comment by fabiobeoni** [comment]
Same here with Flutter 2.1 stable channel targeting Linux Desktop. 

BTW great plugin, thanks for it.

**Comment by Purus** [comment]
Same with Flutter stable 2.0.4 for Android.

**Comment by singerdmx** [comment]
This repo has been inactive for months.  See https://github.com/memspace/zefyr/issues/409#issuecomment-790671992

Just FYI to save your time here.

**Comment by pulyaevskiy** [comment]
Please use zefyr 1.0.0-rc.1 which works with Flutter 2.8.
