### ISSUE TITLE
Run failed with Flutter 2.0

### ISSUE THREAD

**Issue by DylanStouls** [memspace/zefyr#489]
## Description
Hi,
I tried to use zephyr 0.12.0 on a new flutter 2.0 project and it looks like it doesn't work.
Is flutter 2.0 supported or is it planned to be any time soon ?

## Steps to Reproduce

1. Create a new flutter 2.0 project
2. Follow this guide until step 4 : https://zefyr-editor.gitbook.io/docs/quick-start
3. `$ flutter run`

## Logs

With Chrome : 
```
Launching lib/main.dart on Chrome in debug mode...
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.12.0/lib/src/widgets/s
election.dart:659:42: Error: Too few positional arguments: 8 required, 7 given.
    final toolbar = controls.buildToolbar(                              
                                         ^                              
Waiting for connection from debug service on Chrome...             15,0s
Failed to compile application.
```

With Android SDK 30 : 
```
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.12.0/lib/src/widgets/selection.dart:659:42: Error: Too few positional arguments: 8 required, 7 given.
    final toolbar = controls.buildToolbar(                              
                                         ^                                                          
                                                                        
FAILURE: Build failed with an exception.  
```

With iPhone 12 Pro Max Emulator :
```
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.12.0/lib/src/widgets/selection.dart:659:42: Error: Too few positional arguments: 8 required, 7 given.
        final toolbar = controls.buildToolbar(
                                             ^

    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```

## Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by singerdmx** [comment]
![image](https://user-images.githubusercontent.com/122956/110013499-8cae2280-7cd6-11eb-9b14-7ba24668e9e0.png)

**Comment by davidAg9** [comment]
so it is discontinued I guess 
....a great package dies

**Comment by zeusbaba** [comment]
yes I had many issues caused by this project not being actively maintained. 
since then I've been maintaining my own fork https://github.com/beerstorm-net/zefyr and recently updated it for Flutter 2 as well! Feel free to use it   
```
zefyr:
    git:
      url: git://github.com/beerstorm-net/zefyr.git
      path: packages/zefyr/
```

**Comment by singerdmx** [comment]
[flutter-quill ](https://github.com/singerdmx/flutter-quill) is fully compatible with Quill. It is under MIT license and no constraint for commercial use for anyone.
If you do not have Zefyr-based production data yet, it is a better choice.

**Comment by DylanStouls** [comment]
Thank you guys for your responses.
I see that you are all unanimous and I guess that you are right. At least, [statistics](https://github.com/memspace/zefyr/graphs/contributors?from=2018-07-08&to=2021-03-06&type=c) are going on the same way.

I will close this issue since the conversation is going to be duplicated [with this one](https://github.com/memspace/zefyr/issues/409)

**Comment by zeusbaba** [comment]
> [flutter-quill ](https://github.com/singerdmx/flutter-quill) is fully compatible with Quill. It is under MIT license and no constraint for commercial use for anyone.
> If you do not have Zefyr-based production data yet, it is a better choice.

well done @singerdmx , I'll have a look at your repo as well.  
In my case, I have to maintain my fork for some more time, because I've published apps which depend on `zefyr` which needs to be up2date.
