### ISSUE TITLE
Breaking Change in latest url_launcher update - version solving failed.

### ISSUE THREAD

**Issue by shashkiranr** [memspace/zefyr#49]
Version Solving failed because I am using the latest url_launcher package.

```
Because project depends on zefyr ^0.2.0 which depends on url_launcher ^3.0.0, url_launcher ^3.0.0 is required.
So, because project depends on url_launcher ^4.0.1, version solving failed.

pub get failed (1)
```

**Comment by pulyaevskiy** [comment]
Thanks for submitting. I've just published new version of `zefyr` (0.3.0) which comes with some new features and also upgrades `url_launcher` dependency.

Note that there is a breaking change in this release but upgrading should be fairly straightforward.

Check the changelog for details. I've also wrote a blog post with more details here:
https://medium.com/@pulyaevskiy/zefyr-0-3-embedding-and-decorating-456e634449a6
