### ISSUE TITLE
Dependency url_launcher

### ISSUE THREAD

**Issue by hadi20sa** [memspace/zefyr#491]
Please update the url_launcher dependency version

**Comment by amantoux** [comment]
I'm working on null safety along with the upgrade to Flutter 2
I'll make sure to include this

**Comment by singerdmx** [comment]
Are u sure your pull request will be accepted?

**Comment by singerdmx** [comment]
This repo hasn't accepted any pull request for months

**Comment by amantoux** [comment]
I'm still hopeful
Would you be so kind as to refrain from spamming discussions?
Thank you

**Comment by pulyaevskiy** [comment]
Please see `1.0-rc.*` releases on Pub for latest updates of Zefyr package.

https://pub.dev/packages/zefyr/versions/1.0.0-rc.1

url_launcher dependency is now on latest.
