### ISSUE TITLE
Read data from Cloud firestore

### ISSUE THREAD

**Issue by radim10** [memspace/zefyr#499]
In my app, I save the note to Firebase Cloud Firestore as a stringified JSON:
` Future updateFirestore(contents) async {
    final contents = jsonEncode(_controller
        .document); 
    await DatabaseService()
        .updateNote(widget.data['docId'].toString(), contents);
  }`

This example saves to firestore: `[{"insert":"FIrst text\nSec\nThis is heading "},{"insert":"\n","attributes":{"heading":1}}]`

How to correctly read the JSON in the editor so it will properly display the content?
I tried this, but it does not work as expected (in this case it gets the data from parent widget):
`NotusDocument _loadDocument() {
    var note = jsonDecode(widget.data['note']);
    final Delta delta = Delta()..insert("$note\n");
    return NotusDocument.fromDelta(delta);
  }`

The editor displays the content like this. 
How to format the data from Firestore correctly for the Zefyr editor?
![image](https://user-images.githubusercontent.com/62602887/112322325-15562800-8cb1-11eb-8b8d-22da580cb475.png)

**Comment by singerdmx** [comment]
This repo has been inactive for months.  See https://github.com/memspace/zefyr/issues/409#issuecomment-790671992

Just FYI to save your time here.

**Comment by radim10** [comment]
OK, thanks. Will use flutter-quill instead.
