### ISSUE TITLE
maxLines

### ISSUE THREAD

**Issue by ivtod** [memspace/zefyr#50]
Hi @pulyaevskiy,
what about having the ZefyrField height to not be fixed but to expand based on the content?
Just like a TextField behavior setting maxLines to null to allow it to auto grow vertically.

**Comment by ivtod** [comment]
Hi @pulyaevskiy,
any news on this?

**Comment by aldo** [comment]
is there a way to achieve this? I think this is a much needed feature to make this package more flexible and suitable for more use cases

**Comment by smarteertech** [comment]
+1 We need this feature as well. Is there any quick work around?

**Comment by cgestes** [comment]
Maybe you can monitor the changes and forbid them when they add more lines than you want?

**Comment by pulyaevskiy** [comment]
This is address in the 1.0-dev branch by adding `minHeight` and `maxHeight` properties to the editor, please see https://github.com/memspace/zefyr/issues/409 for details about 1.0.

Closing this and will update when the first dev release of 1.0 is out.
