### ISSUE TITLE
Depends on url_launcher ^6.0.3

### ISSUE THREAD

**Issue by khmergeo** [memspace/zefyr#501]
Hello, 

I got errors when upgrading the latest version of another package, The special is url_launcher.

1. Running "flutter pub get" in my project
2. I used url_launcher: ^6.0.3
3. Because another package of Firebase required url_launcher ^6.0.0

## Error Logs

Because zefyr >=0.4.0 depends on url_launcher ^5.0.0 and projectName depends on url_launcher ^6.0.3, zefyr >=0.4.0 is forbidden.

So, because projectName depends on zefyr ^0.12.0, version solving failed.

pub get failed (1; So, because projectName depends on zefyr ^0.12.0, version solving failed.)

## flutter doctor -v

[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-KH)
    • Flutter version 2.0.3 at /Users/khievkimkhun/Documents/flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/khievkimkhun/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

**Comment by pulyaevskiy** [comment]
Zefyr `1.0-rc.1` depends on latest version of url_launcher. Please consider upgrading your project to work with this version.
