### ISSUE TITLE
Support for Flutter 2.0

### ISSUE THREAD

**Issue by AcnoSaga** [memspace/zefyr#502]
### Support for Flutter 2.0
In the file `lib/src/widgets/selection.dart` at line 659:

`final toolbar = controls.buildToolbar(
      context,
      editingRegion,
      block.preferredLineHeight,
      midpoint,
      endpoints,
      widget.selectionOverlay,
      widget.clipboardStatus,
    );`

Is causing errors, since buildToolbar now takes 8 arguments instead of 7.

This needs some simple fixing.

**Comment by singerdmx** [comment]
This repo has been inactive for months.  See https://github.com/memspace/zefyr/issues/409#issuecomment-790671992

Just FYI to save your time here.

**Comment by sleepreading** [comment]
Wanna save you time? Just keep away from this shit library!

**Comment by cgestes** [comment]
> Wanna save you time? Just keep away from this shit library!

Man that's very rude... This library is a lot of code of good quality. As far as I know the best code quality and architecture for a rich text editor in native flutter.
It is a big task that took a lot of time and research. Please be reapectuf of the people that dix put up the great work.

Only issue here is that it is missing maintainers.

**Comment by featzima** [comment]
Please try [Zefyrka package](https://pub.dev/packages/zefyrka) instead of this one. 

Zefyrka is a fork of Zefyr package with the following improvements:
- support of Flutter 2.0
- opt-in the null safety
- text color
- background color
- paragraph alignment
- paragraph indentation

**Comment by pulyaevskiy** [comment]
Zefyr now compiles with Flutter 2.x (stable version).
