### ISSUE TITLE
Build fail on latest version of FlutterError: The non-abstract class 'RawEditorState' is missing implementations for these members: ...

### ISSUE THREAD

**Issue by enomars** [memspace/zefyr#505]
## Steps to Reproduce

1. ... Build fail on latest version of Flutter
2. ...
3. ...

## Logs

Running Gradle task 'assembleDebug'...
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/editor.dart:676:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.userUpdateTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
../flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/editor_selection_delegate_mixin.dart:25:8: Error: The method 'RawEditorStateSelectionDelegateMixin.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
../flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/editor.dart:676:7: Error: The implementation of 'hideToolbar' in the non-abstract class 'RawEditorState' does not conform to its interface.
class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/editor.dart:676:7: Context: The method 'EditorState with AutomaticKeepAliveClientMixin, WidgetsBindingObserver, TickerProviderStateMixin, RawEditorStateKeyboardMixin, RawEditorStateTextInputClientMixin, RawEditorStateSelectionDelegateMixin.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
class RawEditorState extends EditorState
      ^
../flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/editor.dart:807:51: Error: A value of type 'bool' can't be assigned to a variable of type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
        onKey: (node, event) => _keyboardListener.handleKeyEvent(event));
                                                  ^
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/editor.dart:855:53: Error: A value of type 'bool' can't be assigned to a variable of type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('../flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
          onKey: (node, event) => _keyboardListener.handleKeyEvent(event));
                                                    ^
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/text_line.dart:44:47: Error: No named parameter with the name 'nullOk'.
      locale: Localizations.localeOf(context, nullOk: true),
                                              ^^^^^^
../flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
../flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-1.0.0-dev.2.0/lib/src/widgets/text_selection.dart:349:46: Error: Too few positional arguments: 8 required, 7 given.
        child: selectionControls.buildToolbar(
                                             ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
Exception: Gradle task assembleDebug failed with exit code 1

flutter doctor -v
[√] Flutter (Channel master, 2.3.0-1.0.pre.264, on Microsoft Windows [Version 10.0.19041.928], locale zh-HK)
    • Flutter version 2.3.0-1.0.pre.264 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b3f7ebe069 (2 days ago), 2021-05-08 08:54:02 +0800
    • Engine revision f57e986aa8
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Chris\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.0)
    • VS Code at C:\Users\Chris\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • LG H870DS (mobile) • LGH870DSUa8fe051e • android-arm64  • Android 7.0 (API 24)
    • Chrome (web)       • chrome            • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)         • edge              • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!

**Comment by singerdmx** [comment]
This repo has been inactive for months.  See https://github.com/memspace/zefyr/issues/409#issuecomment-790671992

Just FYI to save your time here.

**Comment by featzima** [comment]
Please try [Zefyrka package](https://pub.dev/packages/zefyrka) instead of this one. 

Zefyrka is a fork of Zefyr package with the following improvements:
- support of Flutter 2.0
- opt-in the null safety
- text color
- background color
- paragraph alignment
- paragraph indentation

**Comment by pulyaevskiy** [comment]
Zefyr 1.0.0-rc.1 works with latest stable Flutter 2.8.

**Comment by AndyEverLie** [comment]
> #409 (comment)

Fk You Immediately 😅
For Your Information
