### ISSUE TITLE
Zefyr not working

### ISSUE THREAD

**Issue by SrinivasAttili84** [memspace/zefyr#507]
## Steps to Reproduce
Added latest zefyr 0.12.0 pub, run the code 
## Logs
** BUILD FAILED **
Xcode's output:
↳
    ../../../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.12.0/lib/src/widgets/selection.dart:39:7: Error: The non-abstract class 'ZefyrSelectionOverlayState' is missing implementations for these members:
     - TextSelectionDelegate.userUpdateTextEditingValue
    Try to either
     - provide an implementation,
     - inherit an implementation from a superclass or mixin,
     - mark the class as abstract, or
     - provide a 'noSuchMethod' implementation.
    class ZefyrSelectionOverlayState extends State<ZefyrSelectionOverlay>
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../SDK/flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
      void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ../../../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.12.0/lib/src/widgets/selection.dart:117:8: Error: The method 'ZefyrSelectionOverlayState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
      void hideToolbar() {
^
    ../../SDK/flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
      void hideToolbar([bool hideHandles = true]);
           ^
    ../../../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.12.0/lib/src/widgets/selection.dart:659:42: Error: Too few positional arguments: 8 required, 7 given.
        final toolbar = controls.buildToolbar(
                                             ^
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Flutter' from project 'Pods')

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.2.0 at /Users/srinivasattili/Documents/Flutter/SDK/flutter
    • Framework revision b22742018b (4 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Student (mobile) • 754BEB4B-4E3C-40F2-A85F-D7CDAF556D92 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)     • chrome                               • web-javascript • Google Chrome
      90.0.4430.212

! Doctor found issues in 2 categories.

**Comment by glynskyi** [comment]
Please try [Zefyrka package](https://pub.dev/packages/zefyrka) instead of this one. 

Zefyrka is a fork of Zefyr package with the following improvements:
- support of Flutter 2.0
- opt-in the null safety
- text color
- background color
- paragraph alignment
- paragraph indentation

**Comment by pulyaevskiy** [comment]
Please see `1.0-rc.*` releases on Pub for latest updates of Zefyr package. 

https://pub.dev/packages/zefyr/versions/1.0.0-rc.1
