### ISSUE TITLE
How can i show HTML text in Editor 

### ISSUE THREAD

**Issue by vksBhardwaj** [memspace/zefyr#51]
Hi,

I m really stuck here. I don't know how can i show predefined HTML text in Editor With Proper format
Any help would be appreciable 

Dummy HTML Text : 

```html
<br />\n<strong><u>X-RAY ANKLE JOINT AP/LAT VIEW</u></strong><br />\nNo evidence of fracture is seen.<br />\nBone density is normal<br />\nVisualized bones are normal.<br />\n <br />\n <br />\n<strong>IMPREESION: FINDINGS ARE S/O NORMAL STUDY.</strong> <br />\n<strong><u>X-RAY ANKLE JOINT AP/LAT VIEW</u></strong><br />\nNo evidence of fracture is seen.<br />\nBone density is normal<br />\nVisualized bones are normal.<br />\n <br />\n <br />\n<strong>IMPREESION: FINDINGS ARE S/O NORMAL STUDY.</strong> <br />\n<strong><u>X-RAY ANKLE JOINT AP/LAT VIEW</u></strong><br />\nNo evidence of fracture is seen.<br />\nBone density is normal<br />\nVisualized bones are normal.<br />\n <br />\n <br />\n<strong>IMPREESION: FINDINGS ARE S/O NORMAL STUDY.</strong> <br />\n<strong><u>X-RAY ANKLE JOINT AP/LAT VIEW</u></strong><br />\nNo evidence of fracture is seen.<br />\nBone density is normal<br />\nVis
```

**Comment by pulyaevskiy** [comment]
Zefyr (and Notus) does not support importing any HTML at this point. You'd have to convert your HTML into a valid Delta and then use that Delta to create a document with `NotusDocument.fromDelta`.

Since there is no guarantee what structure is in provided HTML it would be very hard to come up with a generic and robust HTML converter, especially if it contains any tags that cannot be expressed in Notus at this point (like tables, for instance).

**Comment by vksBhardwaj** [comment]
Thanks for replay @pulyaevskiy That means we can't import any type of HTML in Zefyr Editor. Obviously we can't convert big HTML into Delta.
is there any way or any other Editor in i can use in flutter

**Comment by pulyaevskiy** [comment]
I'm not aware if there are any other rich text editors with support for HTML available.

As a general rule, I'd recommend to use Deltas as a source of truth representation if possible. It is fairly straightforward to convert Delta into any other format, including HTML. And it's significantly harder the other way around.

> Obviously we can't convert big HTML into Delta.

It depends. If your HTML is structured in a consistent way, e.g. there is a limited set of HTML tags and fixed layout then there is a chance you can come up with specialized converter that creates proper Delta from HTML source.

In your above example I see only `<strong>`, `<u>` and `<br>` tags are being used. For this subset it should be totally doable to write a HTML-to-Delta converter. With one caveat that "underline" style is not supported yet by Zefyr/Notus.  

Overall, Notus documents in their current state should be able to represent following HTML tags (when converted to Delta): `b` (`strong`), `i` (`em`), `ul` and `ol` (with `li`), `blockquote`, `img`, `a`, `h1`, `h2`, `h3`, `pre` and `hr`.

**Comment by pulyaevskiy** [comment]
Closing this issue as there seems to be no actionable outcome at this point.

It is unlikely we can implement generalized HTML-to-Delta converter for any arbitrary HTML input.

**Comment by bettkipronoh** [comment]
Incase somebody else has the same concern, use this package `notustohtml` and do conversions as below 
`final converter = NotusHtmlCodec();

String html = converter.encode(myNotusDocument.toDelta()); // HTML Output
`
or 
`final converter = NotusHtmlCodec();

Delta delta = converter.decode(myHtmlString); // Zefyr compatible Delta
NotusDocument document = NotusDocument.fromDelta(delta); // Notus document ready to be loaded into Zefyr
`
