### ISSUE TITLE
Selection handles are still visible when scrolled out of view port

### ISSUE THREAD

**Issue by amantoux** [memspace/zefyr#530]
## Steps to Reproduce

1. Select some text
2. Scroll until text is not visible
3. Selection handles are displayed out of view port

<img width="469" alt="capture" src="https://user-images.githubusercontent.com/17318211/132940601-a90e1b4f-96ab-4b1b-9777-48fd8f01e955.png">

**Comment by amantoux** [comment]
@pulyaevskiy I believe this should be added to 1.0 project

**Comment by nipunasudha** [comment]
I think the issue here is, Zefyr does not use its own `Overlay` widget for the selection handles & other overlays. Instead it uses the default `Overlay` in the navigator. To clip the handles inside the editor area, Zefyr should use its own one. Please correct me if I'm wrong.
