### ISSUE TITLE
Swapping handles when dragging a handle should be prevented

### ISSUE THREAD

**Issue by amantoux** [memspace/zefyr#531]
When dragging the **end** handle above the **start** handle, the selection is lost or behaves unexpectedly.
In case where **start** (resp. **end**) handle is moved:

 - after (resp. before) the **end** (resp. **start**) handle on the same line, the selection should be reduced to the character before (resp. after) the other handle
 - after (resp. before) the **end** (resp. **start**) handle on some line below (resp. above), the selection should remain unchanged

**Comment by amantoux** [comment]
@pulyaevskiy can we add this to 1.0

**Comment by pulyaevskiy** [comment]
Added to the project.
