### ISSUE TITLE
The non-abstract class 'InputConnectionController' is missing implementations for these members:

### ISSUE THREAD

**Issue by bravekingzhang** [memspace/zefyr#58]
## Steps to Reproduce

Zefyr not work well on flutter `master channel ` ,some fun should be implemented.

If I change channel to stable ,then ,It will be ok.

## Logs

```
[31mCompiler message:[39m
[31mfile:///home/travis/.pub-cache/hosted/pub.dartlang.org/zefyr-0.3.0/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:[39m
[31m  'updateFloatingCursor'.[39m
[31mTry to either[39m
[31m - provide an implementation,[39m
[31m - inherit an implementation from a superclass or mixin,[39m
[31m - mark the class as abstract, or[39m
[31m - provide a 'noSuchMethod' implementation.[39m

[31mclass InputConnectionController implements TextInputClient {[39m
[31m      ^^^^^^^^^^^^^^^^^^^^^^^^^[39m
[31mflutter/packages/flutter/lib/src/services/text_input.dart:605:8: Context: 'updateFloatingCursor' is defined here.[39m
[31m  void updateFloatingCursor(RawFloatingCursorPoint point);[39m
[31m       ^^^^^^^^^^^^^^^^^^^^[39m
[31mCompiler terminated unexpectedly.[39m
 
Gradle task 'assembleRelease'... Done                       27.7s
[31mGradle task assembleRelease failed with exit code 1[39m
travis_time:end:11f5e7f2:start=1545120577630724689,finish=1545120766298190902,duration=188667466213
[0K[31;1mThe command "flutter build apk" exited with 1.[0m
```

```
before_install:
  - git clone -b master https://github.com/flutter/flutter.git
  - wget http://services.gradle.org/distributions/gradle-4.6-all.zip
  - unzip gradle-4.6-all.zip
#
```

**Comment by pulyaevskiy** [comment]
Thanks for submitting. I'll take a look.

Not sure yet what would be the best way to track master channel of Flutter since there is 1.0 stable version available. The above is a breaking change and it may take a while for it to get into stable channel. 

I'd like to focus on targeting stable Flutter releases now and deliver new Zefyr features that work there first. That said, it would be nice to track latest updates in Flutter specifically for detecting this kind of breaking changes earlier.

**Comment by Skquark** [comment]
Also getting this error, I don't really want to downgrade to stable channel because there were other things I'm doing that depend on the new Flutter version.  I'm on the dev channel, guess I'll wait a bit since I doubt there's much I can do to help you fix the internals there with the updateFloatingCursor.

**Comment by pulyaevskiy** [comment]
I will be looking at this today-tomorrow. Likely what would happen is I’ll use similar branching model to what Flutter uses.

This means that folks who are using dev channels will have to use git dependency for Zefyr, hopefully that’s not big of a deal.

**Comment by pulyaevskiy** [comment]
I've just pushed an update to `master` branch which fixes this issue. This should unblock you guys.

To upgrade in your project you'd need to change dependency in your pubspec to following:

```yaml
dependencies:
  zefyr:
    git:
      url: git@github.com:memspace/zefyr.git
      path: packages/zefyr
```

Moving forward `master` branch in this repo will be tracking `master` branch in Flutter.
Most development will happen off of `beta` branch, releases will also be based on the state of `beta` branch. I will be keeping `master` up to date with all recent changes in `beta`.

**Comment by pulyaevskiy** [comment]
Closing this as there is probably not much else I can do here.

Still need to actually implement the new `updateFloatingCursor` method, but that can be done separately.

**Comment by pulyaevskiy** [comment]
Sorry about that. I had to change branching rules and you need to set branch name to `flutter-master` in order for this to work:

```yaml
dependencies:
  zefyr:
    git:
      url: git@github.com:memspace/zefyr.git
      path: packages/zefyr
      ref: flutter-master
```

**Comment by xscs709560271** [comment]
i meet the same problem.
then i change my dependency as following:
```
dependencies:
  zefyr:
    git:
      url: git@github.com:memspace/zefyr.git
      path: packages/zefyr
      ref: flutter-master
```

but when i get package,it shows some error:
```
Git error. Command: git rev-list --max-count=1 flutter-master
fatal: ambiguous argument 'flutter-master': unknown revision or path not in the working tree.
```

**Comment by pulyaevskiy** [comment]
@xscs709560271 did you get your issue resolved or is it still a problem? One suggestion I have is to replace `url` value with https://github.com/memspace/zefyr.git
