### ISSUE TITLE
Feature request: ZefyrEmbedBuilder add ZefyrController parameter

### ISSUE THREAD

**Issue by taojoe** [memspace/zefyr#603]
make ZefyrEmbedBuilder add ZefyrController as third parameter,  so the embed builder can change itself by controller.

it's required when building a image cropper or image resizer.

```
typedef ZefyrEmbedBuilder = Widget Function(
    BuildContext context, EmbedNode node, ZefyrController controller);

```

**Comment by cgestes** [comment]
Hi,

not sure what's the official reason for the API.

Just in case you can do something along those lines:

```dart
            ZefyrEditor(
              controller: controller,
              focusNode: focusNode,
              embedBuilder: (context, node) => yourEmbedBuilder(context, node, controller),
            ),

```
