### ISSUE TITLE
Could this be also used with AngularDart for web ?

### ISSUE THREAD

**Issue by suexcxine** [memspace/zefyr#65]
Many apps now have both web client and mobile clients.

**Comment by pulyaevskiy** [comment]
Good question. At this point, it's not possible, but I'm exploring options here.

The most promising option at this point is if Hummingbird actually comes out, which allows compiling Flutter apps to web. But we need to wait for it to know for sure.

The next best option is probably to build a separate JS version using building blocks of Quill.js editor, but this requires some additional research. I have not spent time on this yet.

I'm currently focused on addressing several feature requests and getting the editor from "early preview" to "beta" state in terms of feature completeness.

**Comment by pulyaevskiy** [comment]
Closing this for now assuming that the question was answered above.

**Comment by darshanDevrai** [comment]
@pulyaevskiy 
Could Zefyr work with angular port of quilljs?
Like [https://github.com/KillerCodeMonkey/ngx-quill](https://github.com/KillerCodeMonkey/ngx-quill)

**Comment by pulyaevskiy** [comment]
@darshanDevrai There are several differences between Zefyr and Quill in how they store style information. So, in short, these editors are not interchangeable and will likely not work together.

Though, it might be worth investigating if Zefyr could potentially work using "quill" protocol.
