### ISSUE TITLE
Tapping on the blank space does not make the editor focused

### ISSUE THREAD

**Issue by xcffl** [memspace/zefyr#7]
Tapping on the blank space of zefyr editor does not make the editor focused, which means when there is no text, it will be hard to make it focused.

Really hope tapping on anywhere of the editor will make the editor focused.

**Comment by pulyaevskiy** [comment]
Thanks for taking time to report this.

This is a known issue and is tracked in #4 .

I'll close this one as a duplicate but feel free to +1 and subscribe to #4.

**Comment by xcffl** [comment]
That's great.
