### ISSUE TITLE
KeyBoard Issue 

### ISSUE THREAD

**Issue by Nivas78** [memspace/zefyr#74]
KeyBoard issues,
Please guide me 
![issue](https://user-images.githubusercontent.com/6534521/51531051-6a444c80-1e62-11e9-9723-4f7f4e1b0917.png)

**Comment by pulyaevskiy** [comment]
I was not able to reproduce this on my end.

Could you provide more details, including:

1. Version of Zefyr
2. Version of Flutter (output of `flutter doctor)
3. Device used for the above screenshot
4. Concrete steps to reproduce this issue

**Comment by pulyaevskiy** [comment]
> Library : jp.wasabeef:richeditor-android:1.2.2

In this case I’d recommend contacting the author of that library to resolve your issue.

This repository is for issues related to Zefyr editor which only works with Flutter. You seems to be using some native android library so I can’t help with that.

**Comment by Nivas78** [comment]
> > Library : jp.wasabeef:richeditor-android:1.2.2
> 
> In this case I’d recommend contacting the author of that library to resolve your issue.
> 
> This repository is for issues related to Zefyr editor which only works with Flutter. You seems to be using some native android library so I can’t help with that.

Yes I am using Android Native.

Any Author Information,Mail
