### ISSUE TITLE
Q: How to set custom toolbar theme

### ISSUE THREAD

**Issue by rafalolszewski94** [memspace/zefyr#79]
How can I set custom toolbar theme ?

I couldn't find any documentation for this, and I would like to change background color of it.

**Comment by pulyaevskiy** [comment]
Make sure to look at examples in `example/` folder.

This bit in particular:

https://github.com/memspace/zefyr/blob/8ecb5970b2b1a931d969182a456448988b12c003/packages/zefyr/example/lib/src/full_page.dart#L61-L69


I agree that a doc on theming would be helpful though.

**Comment by rafalolszewski94** [comment]
That helped a lot! With a success 😄 

Example:
```dart
return Scaffold(
  appBar: AppBar(
    title: Text('My App'),
  ),
  child: ZefyrScaffold(
    child: ZefyrTheme(
      data: new ZefyrThemeData(
        cursorColor: Colors.blue,
        toolbarTheme: ZefyrToolbarTheme.fallback(context).copyWith(
          color: Colors.grey.shade800,
          toggleColor: Colors.grey.shade900,
          iconColor: Colors.white,
          disabledIconColor: Colors.grey.shade500,
        ),
      ),
      child: Text('My App'),
    ),
  ),
);
```
