### ISSUE TITLE
Signing for ios

### ISSUE THREAD

**Issue by gedw99** [memspace/zefyr#8]
I got an error in xcode when I tried to archive about the 2 plugin that this project uses.

I don't have it to copy paste ( sorry but was last night ).
But it was referring to a folder called "derived data".

Did you hit this for iOS archiving ?

**Comment by pulyaevskiy** [comment]
I did not see issue with archiving for iOS.

This project is written 100% in Dart so there is no native side component in it (yet) so it would be strange for Zefyr to cause such errors.

I do have an iOS app which successfully builds and archives for iOS.

Wondering if you have more details on those errors?

**Comment by gedw99** [comment]
Wow. Sorry about this.
It's crazy then that I am getting xcode yelling about 2 plugins.
Must be my setup.
I will close this and check my setup.

Thanks again ...
