### ISSUE TITLE
Upgrade image_picker and url_launcher version of zefyr

### ISSUE THREAD

**Issue by Panthro** [memspace/zefyr#80]
## Steps to Reproduce

1. add `image_picker: ^0.5.0+3`
2. add `zefyr: 0.3.1`
3 `flutter packages get`

## Logs

```
Because zefyr 0.3.1 depends on image_picker ^0.4.5 and xxx depends on image_picker ^0.5.0+3, zefyr 0.3.1 is forbidden.
So, because xxx depends on zefyr 0.3.1, version solving failed.
```

**Comment by Panthro** [comment]
I'm not sure of all the changes it implies, as the new version is using androidx :-)

**Comment by MaterialTime** [comment]
This happens to me aswell

**Comment by pulyaevskiy** [comment]
Thanks for reporting! Will take a look tomorrow and reply here with an update.

**Comment by pulyaevskiy** [comment]
Sorry for the delay here. I just published `0.4.0` with upgraded dependencies.

You're probably aware but this is a breaking change which requires migrating to AndroidX. See changelog for more details.

I also filed #82 to remove dependency on both plugins which should simplify upgrade story in the future.

**Comment by sabawoon-baryal** [comment]
@Panthro did you find any solution to this?

**Comment by stemuk** [comment]
@pulyaevskiy I know its tedious work, but could you maybe publish a new version with upgraded dependencies or maybe allowing `image_picker: any` would work too. The latest version is image_picker 0.6.0+17, zefyr is currently depending on 0.5.0.

**Comment by Luppakorva** [comment]
@pulyaevskiy would really appreciate if you could please update to latest image_picker version as well?
