### ISSUE TITLE
Error: The non-abstract class 'InputConnectionController' is missing implementations for these members: - 'updateFloatingCursor'

### ISSUE THREAD

**Issue by MaterialTime** [memspace/zefyr#86]
## Steps to Reproduce

1. Upgrade Flutter to Stable build 1.2
2. Build/Run

## Logs

The error is as follows

```
Error: The non-abstract class 'InputConnectionController' is missing implementations for these members: - 'updateFloatingCursor'
```

**Comment by nullptrjzz** [comment]
Same problem. I cannot use it on Flutter 1.2.1 although I have tried to implement 'updateFloatingCursor' in source codes. (Maybe I wrongly used ZefyrEditor)

**Comment by pulyaevskiy** [comment]
Thanks for reporting. I'm aware of this and should have a fix published today/tomorrow. Sorry for the delay.

**Comment by MaterialTime** [comment]
Hey, just wondering whether or not you've gotten a fix ready yet.

**Comment by dasmikko** [comment]
I would also love to know when this is fixed, I would really like to use this package in my app.

**Comment by siamflix** [comment]
Hello 👋 we need you.
We waiting for fixing this please. Thank you.

**Comment by pulyaevskiy** [comment]
Hey guys, sorry for the delay here. 

As a workaround you can try and put a dependency override in your pubspec and point to flutter-master branch in this repo.

**Comment by pulyaevskiy** [comment]
Details can be found here:

https://github.com/memspace/zefyr/issues/58#issuecomment-449586072

**Comment by pulyaevskiy** [comment]
I just released zefyr 0.5.0 which should work with Flutter 1.2.1 (stable).

Make sure to look at the changelog as there are quite a few changes in this release, including breaking.

Closing this as resolved. Feel free to file new issues if there is still something not working.

**Comment by jinfagang** [comment]
```
zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error: The
non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/jintian/development/flutter/packages/flutter/lib/src/services/text_input.dart:658:8: Context:
'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();
       ^^^^^^^^^^^^^^^^
```

**Comment by elgammalqa** [comment]
Same issue here 
Compiler message:
../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/li
b/src/widgets/input.dart:11:7: Error: The non-abstract class
'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

**Comment by function1983** [comment]
**temporary patch for 1.12 stable**
Credit to whoever created it. I own nothing.
```
zefyr:
    git:
      url: git@github.com:wangbo4020/zefyr.git
      path: packages/zefyr
      ref: master
```

**Comment by namchuai** [comment]
I'm facing this problem with 1.12.13+hotfix.9 on iOS build.

**Comment by kannel-outis** [comment]
> Same issue here
> Compiler message:
> ../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/li
> b/src/widgets/input.dart:11:7: Error: The non-abstract class
> 'InputConnectionController' is missing implementations for these members:
> 
> * TextInputClient.connectionClosed
>   Try to either
> * provide an implementation,
> * inherit an implementation from a superclass or mixin,
> * mark the class as abstract, or
> * provide a 'noSuchMethod' implementation.

I'm facing this exact problem RN, I'm using the updated version of flutter

**Comment by cgestes** [comment]
details to fix all those issues provided in other bugs. Sorry it is not easier. We should try making a release at some point...

**Comment by softmarshmallow** [comment]
whats the status of this?

**Comment by cgestes** [comment]
Status?

The last pub package doesn't build since a long time on flutter master.
The master of zefyr doesn't build either anymore.
It needs those two more fixes:
https://github.com/cgestes/zefyr/commit/6b7372fde657267635139fa5a188dfea9211f8c2
https://github.com/cgestes/zefyr/commit/a40efd5a527cb0645c610a5b5a26473963dd5b3b

**Comment by boinxi** [comment]
any updates?

**Comment by pulyaevskiy** [comment]
Please use master branch of this repo instead of the Pub version.
