### ISSUE TITLE
iOS trackpad doesn't work

### ISSUE THREAD

**Issue by lukepighetti** [memspace/zefyr#88]
Hi there, holding down on the keyboard in iOS does not show the trackpad. This was recently added to Flutter's TextFields so perhaps some of the implementation can be stolen from that?

**Comment by pulyaevskiy** [comment]
You're right. This still needs to be implemented. Thanks for filing!

**Comment by pulyaevskiy** [comment]
Thanks @amantoux for adding support for iOS floating cursor. This is now available in 1.0-dev branch and will be release with the first 1.0-beta, coming soon.

Closing is resolved.
