### ISSUE TITLE
Can not worked for Task lists?

### ISSUE THREAD

**Issue by zxl777** [memspace/zefyr#89]
- [ ] Mercury
- [ ] Venus
- [x] Earth (Orbit/Moon)
- [x] Mars

**Comment by amantoux** [comment]
@pulyaevskiy can we descope this from 1.0 and maybe push it for 2.0?

**Comment by pulyaevskiy** [comment]
I'm actually adding this back to 1.0 as implementation is almost complete in #579

**Comment by pulyaevskiy** [comment]
Merged and released in zefyr `1.0.0-rc.2`.
