### ISSUE TITLE
Basic documentation Missing and Few Queries

### ISSUE THREAD

**Issue by VickySalunkhe** [memspace/zefyr#99]
Can you please provide basic documentation to start from.
 I tried implementing  ZefyrEditor
it required full screen height so not of much use

tried ZefyrField but it requires fixed height.
again not of much help looking for extendable height according to content.

then looked for a way to show the data which is being typed.
Found ZefyrView but not sure how it works.
used ZefyrField and ZefyrEditor but those limitations are not helping out to create a nice user experience. 

**What I am looking forward to know is**

1) Is there a way we can disable some options in toolbar , (for ex, I don't users to add image)
2) How to show the content in another page (content which was generated using ZefyrEditor / ZefyrField)

**Comment by leonetosoft** [comment]
Hello @VickySalunkhe ,
Take a look this tutorial: https://medium.com/@pulyaevskiy/zefyr-0-3-embedding-and-decorating-456e634449a6 to add zefyr editor with other elements.

answering question 2: 
``` 
// to display data 
// note:  enabled: false (no edit mode)
// filled: true  (disable borders input)
// fillColor: Colors.transparent (color of input)

ZefyrField(
      decoration: InputDecoration(
        fillColor: Colors.transparent,
        filled: true,
        labelStyle: TextStyle(fontFamily: String.fromCharCode(1)),
        contentPadding:
        EdgeInsets.only(bottom: 10.0, left: 10.0, right: 10.0),

      ),
      controller: _controller,
      focusNode: _focusNode,
      autofocus: false,
      enabled: false,
      physics: ClampingScrollPhysics(),
    );

```

**Comment by VickySalunkhe** [comment]
Hi @leonetosoft 
I tried the code which you provided.

I am getting this error as you have not mentioned height parameter in ZefyrField

I/flutter (24174): Another exception was thrown: RenderFlex children have non-zero flex but incoming height constraints are unbounded.
I/flutter (24174): Another exception was thrown: RenderBox was not laid out: RenderFlex#d01b2 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (24174): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (24174): Another exception was thrown: RenderBox was not laid out: RenderPadding#9f5f6 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (24174): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.



And that is what the problem is I don't know how long or short my content can be then I seriously cant give a predefined height to the widget.

**Comment by leonetosoft** [comment]
@VickySalunkhe please post your code.

**Comment by ivtod** [comment]
@VickySalunkhe can you please post your code? it may help.
Similar to https://github.com/memspace/zefyr/issues/50 , anyone came up with a solution?

**Comment by pulyaevskiy** [comment]
Pretty late response but still:

> 1. Is there a way we can disable some options in toolbar , (for ex, I don't users to add image)

Not at this point. Note that Zefyr is still an early preview version so there are many things that can be improved. I'm just starting to work on making Zefyr more extensible, which would cover this requirement.

> 2. How to show the content in another page (content which was generated using ZefyrEditor / ZefyrField)

There is now `ZefyrView` which simply renders contents as read-only and allows to embed documents in custom scrollable layouts. Hopefully that'll cover it for you.

Closing this for now, but if you have more questions feel free to re-open or join our [Spectrum chat](https://spectrum.chat/zefyr?tab=posts)
